### ISSUE TITLE
Include examples for linked columns, smart columns, and smart variables?

### ISSUE THREAD

**Issue by backus** [ankane/blazer#10]
The [blazer demo](https://blazerme.herokuapp.com/) is helpful and seems to use smart columns and variables. Any reason for not including the `blazer.yml` file from the demo in this README?  Even if these features are trivial to figure out after a few minutes it is still helpful to have an example.

**Comment by ankane** [comment]
Added better documentation for smart variables, linked columns, and smart columns.  Let me know if it's clear.

**Comment by backus** [comment]
Looks great
