### ISSUE TITLE
Polling option

### ISSUE THREAD

**Issue by ankane** [ankane/blazer#100]
By default, a web server connection is tied up when running queries. To switch to polling:

1. Add [sucker_punch](https://github.com/brandonhilkert/sucker_punch) to your Gemfile
2. Add `async: true` to `config/blazer.yml`

Your app must use a centralized cache like [Memcache](http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore) for this to work with multiple servers.

Outstanding issues
- [ ] Sometimes queries get "lost" (cause not yet known)
- [ ] Not everything SQL returns can be marshaled (like invalid dates). Should store results as `json` with column types.
- [ ] Some result sets can be pretty big. Possibly use `msgpack` for compression (does this make a difference since memcached uses compression?)

**Note:** Polling was chosen over WebSockets because it's significantly easier to set up for developers (no need to configure SSL, separate authentication, etc).

**Comment by seanfcarroll** [comment]
What about an ActionCable solution (would be Rails 5 compatible only of course)

**Comment by ankane** [comment]
ActionCable uses WebSockets, so it has the same drawbacks.

**Comment by ankane** [comment]
Adding in 2.0.
