### ISSUE TITLE
Charts not visible

### ISSUE THREAD

**Issue by seanfcarroll** [ankane/blazer#101]
I'm on Rails 5  -- rails (5.0.0.1), no console errors but no chart at all.

<img width="1357" alt="screen shot 2016-11-08 at 09 45 59" src="https://cloud.githubusercontent.com/assets/11340230/20092398/3de231d8-a598-11e6-8f69-1e09319a6679.png">

(Note I have temporarily rolled back the changes I described in https://github.com/ankane/blazer/issues/50, so am using Blazer, I think, out of the box)

**Comment by ankane** [comment]
Hey @seanfcarroll, please read the docs before filing issues: https://github.com/ankane/blazer#line-chart

**Comment by seanfcarroll** [comment]
Hi there, thanks for the quick response. I think I am being dumb ... I have a count in my query, but no chart appears

> Charts

> Blazer will automatically generate charts based on the types of the columns returned in your  query.

> Line Chart

> 2+ columns - timestamp, numeric(s) - Example

```
SELECT count(*), date_trunc('day',submission_time) FROM submissions s group by  date_trunc('day',submission_time)
```

**Comment by seanfcarroll** [comment]
OK I found the problem. The timestamp field is **timestampz** ie: timestamp with timezone (on Postgres).

**Comment by ankane** [comment]
Sorry @seanfcarroll, think I was in a bad mood on Monday. Both timestamp and timestamptz should work. The time column must come first, then the numeric. I'll make the docs more clear.

**Comment by seanfcarroll** [comment]
Hey @ankane no problem. This is a great gem, and I'll soon do some work to help you out. I can start with https://github.com/ankane/blazer/issues/97 and perhaps also https://github.com/ankane/blazer/issues/98.

I think it would be great to able to drop Blazer into an existing Rails app, also noted here https://github.com/ankane/blazer/issues/49  and here https://github.com/ankane/blazer/issues/50

 I have included it into app but needed to hack the layout a bit to make it work. Different engines approach the problem in different ways. I think the Devise approach is the gold standard for gems without much markup or structure. I also like the [Thredded](https://github.com/thredded/thredded) approach including the ability to override the layout from the initializer. 

The other thought I had was to add an advanced chart, where the user can write the SELECT first, then chose from the returned columns for x and y axis on a chart.

I can start working on some or all of these. My own project is [crowdAI](https://github.com/crowdAI) and we will probably add Blazer into here also.
