### ISSUE TITLE
Failed upgrade from 1.1.0 to 1.7.4

### ISSUE THREAD

**Issue by giedriusr** [ankane/blazer#102]
Hello,

I've just upgraded our blazer from really outdated version 1.1.0 to 1.7.4 and got this:

![image](https://cloud.githubusercontent.com/assets/210713/20168113/a8759260-a728-11e6-8a5b-be20b9744bcd.png)
---
![image](https://cloud.githubusercontent.com/assets/210713/20169649/61c403a2-a731-11e6-83b5-5b0b1f6aebfb.png)
---
![image](https://cloud.githubusercontent.com/assets/210713/20169699/9cf7373c-a731-11e6-9e08-5589ccfffae2.png)

1. My queries disappeared.
2. Doesn't detect schema tables of the main database.
3. Though, I am able to create new Checks with existing Queries.

![image](https://cloud.githubusercontent.com/assets/210713/20176788/120603c6-a752-11e6-9262-696ad1b2206c.png)

Does anyone else facing the same?

**Comment by giedriusr** [comment]
Oh, ok, I see that there are migrations needed for the upgrade. Will try and let you know.

**Comment by giedriusr** [comment]
Ran the migrations, still the same issue. Are there any changes needed for blazer.yml?

**Comment by giedriusr** [comment]
Locally, I am able to see my demo blazer database with local queries, but in production, no. Could it be related to query names? Quotes? Dashes, smth else?

**Comment by ankane** [comment]
It looks like an issue with assets. Can you paste any errors in the JavaScript console?

**Comment by giedriusr** [comment]
I've downgraded to version 1.5 and now are able to see the list of Queries, but when I open one I get a JS error: `Uncaught ReferenceError: runQuery is not defined`. It shows the SQL statement, but at the results part, always "Loading.."

**Comment by ankane** [comment]
I don't think the updated assets are being used. I would investigate there.

**Comment by giedriusr** [comment]
@ankane thank you very much!

**Comment by giedriusr** [comment]
As mentioned above, assets weren't used. thanks.
