### ISSUE TITLE
Improve checks

### ISSUE THREAD

**Issue by ankane** [ankane/blazer#103]
Add ability to alert if more than N rows or less than N rows.

**Comment by hd719** [comment]
Hello there! I am new to open source and I would like to contribute to this project.

**Comment by ankane** [comment]
Hey @hd719, sorry for the (really) delayed response. If you're still interested, the best way to contribute is it to take one of your current pain points with Blazer and try to fix it. If you have specific ideas, feel free to open another issue and we can discuss.
