### ISSUE TITLE
Tracking views

### ISSUE THREAD

**Issue by Brutus9** [ankane/blazer#104]
Hi,

We are using blazer for our reporting, and we are huge fans of it. We are trying to implement view tracking with our website and also would like to track views of blazer to see which stats are viewed more than others. Is there anything in the current setup that makes that possible? Or is this something that needs to be added. 

Kind regards,

Brian

**Comment by ankane** [comment]
Hey @Brutus9, there's no easy way to add analytics code at the moment to views. If you want to view query activity specifically, you can use the `blazer_audits` table.

**Comment by rjrobinson** [comment]
I use the ahoy gem, and the use blazer to query and display those metrics.
