### ISSUE TITLE
Dashboard edit view broken

### ISSUE THREAD

**Issue by buren** [ankane/blazer#108]
I'm seeing 👇,  when editing a dashboard. All the names are blank in the list and if I try to submit the form `POST /blazer/dashboards/` I get `404 Not found`.

<img width="464" alt="screen shot 2016-12-13 at 01 40 41" src="https://cloud.githubusercontent.com/assets/922411/21122877/3bd435aa-c0d5-11e6-893f-0aad02095788.png">

---

I quickly dug into the code and `var dashboardQueries` thats generated by `blazer_js_var`, seems correct. However after Vue has been initialised, `dashboardQueries` is now a Vue object and I've never used `Vue` before so didn't dig any further.

Blazer v1.7.5
I've tested in Chrome 55, Firefox 46 and Safari 9, so it doesn't look like a browser bug.

Thanks for an awesome gem 🙇

**Comment by ankane** [comment]
Do you see any errors in the JavaScript console?

**Comment by buren** [comment]
@ankane nope no errors :/

**Comment by ankane** [comment]
Not sure what it could be. Not seeing this in dev or any of my installations ([public one here](https://blazerme.herokuapp.com/dashboards/1-dashboard-demo/edit)).

**Comment by buren** [comment]
Hm interesting, I guess it must have something to do with our data then.. 

I'll definitely report back here when I find out more, thanks for checking!

**Comment by buren** [comment]
When posting [this line in dashboard controller](https://github.com/ankane/blazer/blob/master/app/controllers/blazer/dashboards_controller.rb#L86) is the issue, so this happens:
```ruby
# My params
params[:query_ids] # => ["", "31"] 
params[:query_ids].map(&:to_i) # => [0, 31]
```

If I add `.reject(&:blank?)` it that works. Shouldn't a blank first item be possible? Or should I open a PR that adds the reject?

Going to try to look into why the query list is empty (still a Vue newbie though..).

**Comment by buren** [comment]
Found it!

For me this is how `dashboardQueries` looks:
```js
var dashboardQueries = [{"query":{"id":108,"creator_id":12,"name":"New users per week (date..." }}]"
```

while your [Heroku demo](https://blazerme.herokuapp.com/dashboards/1-dashboard-demo/edit) its
```js
var dashboardQueries = [{{"id":108,"creator_id":12,"name":"New users per week (date..." }"]
```

so thats why it caused problems.
