### ISSUE TITLE
usage of user_class and user_name

### ISSUE THREAD

**Issue by hovancik** [ankane/blazer#110]
So from what I understand, user_class and user_name are used to populate creator of queries etc. 
I have devise and model AdminUser so I put: 

```
# class name of the user model
user_class: AdminUser

# method name for the user model
user_name: email
```

When I create some query, the creator is empty. Am I doing something wrong? 

ruby 2.3.1
rails 4.2.7.1
blazer 1.7.7

**Comment by davehartnoll** [comment]
This was my understanding too, and if that's correct, I have the same issue. In my case, I have:

```
user_class: System::Admin
user_name: email
```

**Comment by ankane** [comment]
`user_name` is the display name. `user_class` used for in the `belongs_to :creator` association. You probably need to set `user_method`.

**Comment by hovancik** [comment]
Thanks, that worked. 
I created PR https://github.com/ankane/blazer/pull/112 to fix the template and documentation
