### ISSUE TITLE
PostgreSQL array queries clash with Blazer's variable syntax

### ISSUE THREAD

**Issue by peteryates** [ankane/blazer#111]
When attempting to create a query with [PostgreSQL Array Syntax](https://www.postgresql.org/docs/9.1/static/arrays.html), Blazer thinks the array is a variable.

Here's an example; we're looking for all linguists with tag `XYZ`:

```sql
select name, recruitment_tags
from linguists
where recruitment_tags <@ '{XYZ}'
```

Blazer responds with the following:

> Can’t preview queries with variables...yet!

Saving the query results in Blazer's normal behaviour of prompting for input before executing the query, which fails because PostgreSQL complains about the supplied array's syntax being invalid.

Now, I can work around this by using `unnest()` or calling `string_to_array()` and I understand this is niche, vendor-specific functionality but thought it was worth raising, perhaps there's a nicer workaround that I've not considered.

**Comment by ankane** [comment]
You can use array constructor syntax instead of array literal syntax - see https://www.postgresql.org/docs/current/static/arrays.html

**Comment by peteryates** [comment]
Ah, indeed I can. Hadn't come across the constructor syntax in PostgreSQL before, thank you.

For anyone else wondering, this worked for me:

```sql
select name, recruitment_tags
from linguists
where recruitment_tags @> array['XYZ'::varchar];
```
