### ISSUE TITLE
falls back to DATABASE_URL?

### ISSUE THREAD

**Issue by jjb** [ankane/blazer#117]
Looks like it falls back to DATABASE_URL if BLAZER_DATABASE_URL isn't present, even if the yml file is configured to use BLAZER_DATABASE_URL.

a) this is the behavior, right? (if so, great!)
b) if so, then would be nice to have that mentioned in the readme, i'll submit a patch

i looked in the code but i'm not confident about my findings, because i saw this https://github.com/ankane/blazer/blob/master/lib/blazer/data_source.rb#L15

i've only tried blazer in development so far.

**Comment by ankane** [comment]
Hey @jjb, it's designed to fall back in development (so you can get it up in running quickly), but not in production (so you're aware of what database user it's using). Curious to hear how you'd change the readme.

**Comment by jjb** [comment]
👆 check it out
