### ISSUE TITLE
Problem with default_url_options

### ISSUE THREAD

**Issue by crivotz** [ankane/blazer#120]
Hi,  
I have a problem with blazer route if I pass locale with the default_url_options method (from [RailsI18n](http://guides.rubyonrails.org/i18n.html))  
The urls are sst in this way: `/blazer/?locale=enqueries/schema?data_source=main`
```
def default_url_options(options = {})
  { locale: I18n.locale }.merge options
end
```  
Thanks ;)

**Comment by ankane** [comment]
Hey @crivotz, thanks for reporting. It's fixed on master.
