### ISSUE TITLE
Preview table is not working

### ISSUE THREAD

**Issue by mojobiri** [ankane/blazer#123]
Hi. First, thanks for such beautiful software.
Maybe I'm doing something wrong, but "Preview table" drop-down on query edit page does not work for me.
I'm using latest blazer version 1.7.8. I'm using PosrgreSQL and have one data source.
`GET blazer/queries/tables?data_source=main` returns array of table names, but "Preview table" drop-down is empty. Nothing happens on click.

**Comment by ankane** [comment]
Hey @mojobiri, do you see any errors in the JavaScript console?

**Comment by mojobiri** [comment]
No, nothing in the console..

**Comment by ankane** [comment]
Hey @mojobiri, does the schema page show any tables?

**Comment by mojobiri** [comment]
Yes, schema page show all tables.
![image](https://user-images.githubusercontent.com/664081/32540674-746cdab8-c47e-11e7-800d-7e0e66ba02e7.png)

**Comment by ankane** [comment]
Seems like something with JavaScript.

- What browser (including version) are you running? Does it work in other browsers?
- Are you running any extensions (like ad blockers) that could be interfering with it?

**Comment by mojobiri** [comment]
Ubuntu 17.04, Firefox 56.0 (64-bit)
Windows 10, Firefox 56.0.2 (32-bit)
Does not work in latest Chrome as well.
Disabled all extensions - no luck.

**Comment by ankane** [comment]
It works fine with the latest versions of Firefox and Chrome on Mac, and haven't heard any other reports of this, so think you'll have to debug this on your own. Let me know if you find anything.

**Comment by ankane** [comment]
Cleaning up stale issues
