### ISSUE TITLE
Amazon RDS  Bad URI

### ISSUE THREAD

**Issue by muaaz-vf** [ankane/blazer#128]
Hi, 
   My database is hosted via RDS and I have a connection string, I am adding like the documentation postgres://username:password_with_special_characters@rds_path:5432/db_name , the application is running fine. But when I visit blazer/queries/new it gives me error like below, 
`ActionView::Template::Error (bad URI(is not URI?): postgres://username:password_with_special_characters@rds_path:5432/db_name`

Any help will be appreciated how to give the connection string.

Thanks,
Muaaz Rafi

**Comment by ankane** [comment]
Hey @muaaz-vf, you'll need to use percent encoding for special characters. More info here: http://stackoverflow.com/questions/23353623/how-to-handle-special-characters-in-the-password-of-a-postgresql-url-connection
