### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by buren** [ankane/blazer#132]
You've listed under TODO in the [README](https://github.com/ankane/blazer#todo) that you want a standalone version. I've created one here https://github.com/buren/ghost_blazer that can be deployed with a "Deploy to Heroku"-button.

(Uses `BLAZER_USERNAME` and `BLAZER_PASSWORD` for auth.)

**Comment by ankane** [comment]
Thanks @buren, missed this 👍 Very cool. Added a link to the readme.
