### ISSUE TITLE
ActionView::Template::Error (Empty url for data source: main):

### ISSUE THREAD

**Issue by PepeBel4** [ankane/blazer#134]
Hello,
New to Blazer.
I installed on development environment -> working fine.
However, not working on our staging environment with error:

ActionView::Template::Error (Empty url for data source: main):

Our staging database (Postgresql, where Blazer tables are installed) is not configured to listen on port 5432. Is there a way to query the database on Staging, just as it is possible on development,
without having to define the ENV variable?

**Comment by ankane** [comment]
Hey @PepeBel4, the dev convenience is only meant for dev. If the database is on the same machine as Blazer, you can connect through a socket like this: http://stackoverflow.com/questions/27037990/connecting-to-postgres-via-database-url-and-unix-socket-in-rails

**Comment by PepeBel4** [comment]
Hello,

That works!
Super!

Looking forward to more features, as it’s already superb to use the product!

Best regards,
Pascal
