### ISSUE TITLE
Change default time range for start_time & end_time

### ISSUE THREAD

**Issue by marcusg** [ankane/blazer#135]
Is it possible to change the default values for the datepicker values when entering the dashboard? For example: last year instead of last 30 days. Thanks!

**Comment by ankane** [comment]
Hey @marcusg, there's no setting for this right now.

**Comment by marcusg** [comment]
@ankane ok, thanks for the response. Do you think it would be an useful option?

**Comment by ankane** [comment]
I don't personally have a strong need, but can see it being useful to others, so happy to accept a PR if it's done in a clean way.

**Comment by ankane** [comment]
Going to close this since discussion is stale, but previous comment still applies.
