### ISSUE TITLE
Add other chart configurarions

### ISSUE THREAD

**Issue by stupied4ever** [ankane/blazer#139]
First of all, I want to stay thank you for all who worked on this, This gem is amazing and help me  everyday. :) Thank you again.

As I told before, I am using this gem to analize a lot of information we have on our business, and the part that I most miss is the charts configurations. I know the idea to guess the chart type worked until now, but I some cases some manual co figuration would be nice. 

As an example, a em working on a PR that adds the heatmap chart. For this I am using the Mapbox GL and the result is pretty nice, although, the fields I return in the query is the same the map charts uses to guess the chart type. On my pr I also need some co figurations to tell the heatmap size for each color (ex red: 100, orange: 50, green: 10).

My initial idea is that near the  query field we could have other field such as a chart type (with a auto detect default option?) And other custom fields (saved on a Json field?) That could be customized by chart type. 

Probably this kind of configurations would let the controllers and views much simpler, while allow to have many other map types. What do you think ?

**Comment by stupied4ever** [comment]
Sorry for any typo (I am Brazilian writing on a cellphone while I am on a bus, that is really hard)

**Comment by ankane** [comment]
Hey @stupied4ever, I've thought about making it easier to create charts in the UI, but with the existing chart types rather than a new one. Can you give an example of the data format for the heatmap?

**Comment by stupied4ever** [comment]
Hi Andrew, thank you for the attention.

The easy way is just to look the example in API docs
https://www.mapbox.com/mapbox-gl-js/example/heatmap/

Em qua, 29 de mar de 2017 01:22, Andrew Kane <notifications@github.com>
escreveu:

**Comment by ankane** [comment]
Hey @stupied4ever, I was referring to the Blazer data format.

**Comment by stupied4ever** [comment]
@ankane sorry for the late response, I really did not understand what do you mean "Blazer data format", can you give me some clue ?

**Comment by ankane** [comment]
Hey @stupied4ever, I reread your first post and it looks like you included it there.

> the fields I return in the query is the same the map charts uses

So it sounds like only latitude and longitude are used to create the heatmap?

**Comment by ankane** [comment]
Cleaning up stale issues
