### ISSUE TITLE
Question: Configuration for non persistant models

### ISSUE THREAD

**Issue by T-TonyLiang** [ankane/blazer#142]
Hello, I was wondering if there is an option where the queries, dashboards, audits **wouldnt** be saved in the database. 

I'm looking to integrate this in a rails app but don't want to add any tables in my database. I am also okay with losing the functionality that comes with having a persisted model.

All i have so far is:
```
audits: false
```

Thanks in advance.

**Comment by ankane** [comment]
Hey @T-TonyLiang, Blazer doesn't support this. You can always configure Blazer to use a separate database (even something like SQLite) for its data if you want to keep things separate.

**Comment by ankane** [comment]
Something like [nulldb](https://github.com/nulldb/nulldb) could work as well.

**Comment by T-TonyLiang** [comment]
Awesome, thanks for the answer.
