### ISSUE TITLE
Assets not loading properly (Vue not defined)

### ISSUE THREAD

**Issue by FanaHOVA** [ankane/blazer#144]
I've noticed this problem has been brought up before, but couldn't find a solution. Same issue as this: https://github.com/ankane/blazer/issues/102 but I upgraded from 1.5 instead. Error:

```
(index):81 Uncaught ReferenceError: Vue is not defined
    at (index):81
```

Which leads to

```
var app = new Vue({
    el: "#queries",
    data: {
      searchTerm: "",
      more: more,
      updateCounter: 0
    }
```

Which comes from `home.html.erb` in the Blazer gem. If it makes any difference I'm running a fork of the gem where I added Slack hooks: https://github.com/saberespoder/blazer (I'll improve it and post a PR as soon as I have some time, it's pretty ugly now 😛 )

I think this might be related to Vue being initialized before being required, gonna investigate this but if you have any solutions in mind let me know, will keep the issue updated for future reference too. 

Solutions tried:

- [x] Run `rake assets:precompile`
- [x] Make sure javascript is required before `yield` in the `application.html` file.

**Comment by FanaHOVA** [comment]
Well, that was easier than I thought. Disabling Turbolinks fixed the issue :)

**Comment by jeyraof** [comment]
I also run rake assets:precompile but asset not bundled.

How can I fix `Vue not defined` for me?
