### ISSUE TITLE
A chart with "false" as a label shows as blank.

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#150]
I have a chart which graphs 3 lines, `false`, `true`, `null`. Both `false` and `null` don't show the name in the tooltip. `null` being absent mostly makes sense to me, but false should be there (I think). 
Have 2 of 3 lines with only partial labels makes things a bit confusing when the data are very close together.

Hopefully this screenshot makes sense:
![screen shot 2017-04-28 at 1 52 48 pm](https://cloud.githubusercontent.com/assets/1505907/25547086/7b8801f8-2c1a-11e7-9c00-826ca0d6db7c.png)

**Comment by ankane** [comment]
Hey @cycomachead, thanks for reporting. Fixed on master.

**Comment by cycomachead** [comment]
Awesome, thanks for the quick fix! 👍

-- 
Michael Ball
From my iPhone
michaelball.co
