### ISSUE TITLE
Error bars/variance for timeseries

### ISSUE THREAD

**Issue by ibrahima** [ankane/blazer#151]
First of all, Blazer is pretty sweet!

I was wondering if it makes sense to allow users to plot error bars or some other notion of variance on time series plots, eg. like the examples on http://seaborn.pydata.org/generated/seaborn.tsplot.html. I can compute the variance using Postgresql and have that as a column in Blazer, and if it detects eg. columns named foo and foo_var, it could use that information to draw error bars.

This is probably a big feature request, but I just wanted to know if this was something that you might consider adding, especially if I were to write a PR.

Looks like Chart.js doesn't natively support error bars: https://github.com/chartjs/Chart.js/issues/319 but one possibility is to have Blazer automatically create column+var/column-var columns and plot those in a lighter shade, or even abuse stacked plots to make those. It might even be possible to do that without any support in Blazer, but I haven't yet figured out how to refer to those computed aggregate columns for doing further computations (I'm a novice at actual SQL).

Anyway, thanks for the great tool!

**Comment by ibrahima** [comment]
Ah, update on the workaround approach: using a Common Table Expression (eg. https://www.postgresql.org/docs/9.1/static/queries-with.html) lets you compute the variance and then use that for error bars. CTEs are also useful for hiding intermediate variables if you don't want to plot them all.

**Comment by ankane** [comment]
Hey @ibrahima, thanks for the suggestion 👍  What data format are you thinking for this feature? (for instance, scatter chart is 2 columns - both numeric)

**Comment by ankane** [comment]
Cleaning up stale issues
