### ISSUE TITLE
Dashboards: Same Queries with different variables

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#152]
Is there a way to have the same queries appear multiple times on a dashboard with different variables? I realize forking and changing variable names would work, but I was wondering if there were something similar I could do?

This is probably most useful with the ability to save variables in a dashboard, but even right now, it would still nice to be able to compare similar charts.

**Comment by ankane** [comment]
Hey @cycomachead, there's not a way to do this. I've thought about it before, but think it adds too much complexity, especially for the UI. If there's a clean, simple way to do this, happy to review a PR.

**Comment by ankane** [comment]
Cleaning up issues
