### ISSUE TITLE
Change axes and/or CSS

### ISSUE THREAD

**Issue by cd-rum** [ankane/blazer#154]
What'd be the best way to implement chart style options? Either JS or CSS or both, just so we can control the look and feel a little better.

**Comment by ankane** [comment]
Hey @cd-rum, you'd need to fork the gem for this, as I don't think it makes sense to officially support this type of customization. If you have specific suggestions for charts that others could benefit from, happy to consider incorporating them.

**Comment by cd-rum** [comment]
Hey @ankane, no problem there. I've forked it and I'll see what I can come up with—my need is about display for the most part, like some strings have really long names and they're presently being cut off for my client. I'll send a pull request if my fix ends up useful and/or half-decent. Thanks.
