### ISSUE TITLE
Gem::CommandLineError

### ISSUE THREAD

**Issue by dipenpatel235** [ankane/blazer#160]
Below server configuration and version
Centos 7 64 bit Os
Rails 4.2.0
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
 gem -v 2.4.5

Error when hit below command
gem 'blazer'
ERROR:  While executing gem ... (Gem::CommandLineError)

**Comment by ankane** [comment]
Hey @dipenpatel235, I'm not sure what the issue is, but I don't think it's related to Blazer.
