### ISSUE TITLE
Line Chart with Text x-axis

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#161]
I can't tell if there's a related issue to this already...If so, sorry!

I was trying to create a chart to look at YoY growth by month (let's say, of users), and couldn't figure out a way to get a line chart with "partial" dates unless I coerced all my dates to the same year.

```sql
SELECT make_date(2000, extract('month' from created_at)::int, 01) AS month,
       date_part('year', created_at)::text AS year,
       count(*)
FROM users
GROUP BY month, year
ORDER BY year, month;
```

Basically, I'm wondering if there's a way I can get a line chart by having a whole bunch of columns that are just "January"..."December".

**Comment by ankane** [comment]
Hey @cycomachead, line charts only support a time axis right now.
