### ISSUE TITLE
No assets in production, but working in development

### ISSUE THREAD

**Issue by echan00** [ankane/blazer#164]
I'm not 100% certain my issue pertains to blazer since it is related to rails precompile. But I am not seeing any blazer assets in production.

` RAILS_ENV=production bundle exec rake assets:precompile` seems to work fine in development and I see the blazer assets in my 'public/assets/blazer' folder.

I have tried forcing my app to precompile all production assets but I do not see 'public/assets/blazer' folder in production.

**Comment by ankane** [comment]
Hey @echan00, I don't think is an issue with Blazer, but please update the issue if you make any progress so others can benefit.

**Comment by echan00** [comment]
Yes, sorry this is not related. Thanks for closing
