### ISSUE TITLE
IN NEED OF 'Yesterday'

### ISSUE THREAD

**Issue by kdk2121** [ankane/blazer#168]
Hi, our team is using blazer very well, and we think we need "Yesterday" in date range.
It is not only we look for data of yesterday much but since google analytics also support "Yesterday" as date range.

Think **ranges** in
**_variables.html.erb**
should be changed 
```
ranges: {
             “Today”: [dateStr(), dateStr()],
             “Last 7 Days”: [dateStr(6), dateStr()],
             “Last 30 Days”: [dateStr(29), dateStr()]
            },
```
Can you make changes plz?

**Comment by JayTeeSF** [comment]
fwiw, I want "3 Days ago" ...it would be ideal, if that list of ranges (and the default) was configurable.

**Comment by ankane** [comment]
Dup of #135
