### ISSUE TITLE
Variables Dependent on Other Variables?

### ISSUE THREAD

**Issue by blairanderson** [ankane/blazer#170]
Imagine if shopify was using this and wanted to build a dashboard around a single product beneath a store. 

variable1 is `account_id` 
and 
variable2 is `products.id where products.account_id = accounts.id`

**Comment by ankane** [comment]
Hey @blairanderson, it's a neat idea, but don't think it's common enough of a need to add.

**Comment by ankane** [comment]
Also, hope you're doing well.

**Comment by blairanderson** [comment]
Yeah I agree not super common! 

Was thinking about features that would allow sub-users from writing queries without giving full access to the DB, but this probably wouldn't do it. 

Yes i'm doing well, running a small consulting company. What are you up to now?

**Comment by ankane** [comment]
Awesome. I’m doing a lot of open source, trying to write more, and prototyping a few ideas.
