### ISSUE TITLE
ActionController::UnknownFormat: Blazer::QueriesController#run is missing a template for this request format and variant.

### ISSUE THREAD

**Issue by getaclue** [ankane/blazer#172]
Hey man,

First and foremost... thank you for making this! It is amazing.

I went ahead and added amp today to my recent project and it seemed to have affected Blazer.

I added amp by going to
```
config/initializers/mime_types.rb
```
and simply pasted
```rb
Mime::Type.register 'text/html', :amp
```
Everything seemed to be working fine until I went to check my dashboards. They aint seem to be working out of the box. And I am getting the error mentioned above.

Here is the full error:

![image](https://user-images.githubusercontent.com/6380439/31312106-f7cdec44-ab88-11e7-862e-8007b874c3dc.png)

![image](https://user-images.githubusercontent.com/6380439/31312108-135ac11c-ab89-11e7-8cda-3161ad77cdd9.png)

However, everything gets resolved if I simply force `.html` extension.

So, I'm wondering if you would happen to have some insight to what could be potentially breaking this. As I said, adding `.html` works for now so I can live with that but I do want to fix it or mention it in case other people stumble upon this in the future =)

I looked at https://github.com/ankane/blazer/blob/767faefe9d05870e5a18c50d676b7968024a1a27/app/controllers/blazer/queries_controller.rb#L240 and nothing really stood out to me so I came here =)

Thank you,
Alex

**Comment by ankane** [comment]
Hey @getaclue, thanks for reporting 👍  I don't have a great idea of why this breaks dashboards, but happy to merge the fix if you submit a PR.

**Comment by getaclue** [comment]
alrighty, I'll keep digging and report back as I get updates (:

**Comment by ankane** [comment]
Cleaning up stale issues. Please let me know if you found anything @getaclue

**Comment by getaclue** [comment]
@ankane no worries; yeah I haven't had the chance to figure out why yet and it is still there.

**Comment by getaclue** [comment]
ps @ankane i finally figured it out... turns out was on my side.

I added amp support to my app, so in my initializers I had
```rb
Mime::Type.register 'text/html', :amp
```
and then after reading the log over and over I noticed...
```rb
Processing by Blazer::QueriesController#run as AMP
```
so this is where this came from =)

just wanted to update and say finally got to the bottom of this

**Comment by ankane** [comment]
Thanks for following up 👍 Hopefully this can help others
