### ISSUE TITLE
Blazer URLs behind proxy

### ISSUE THREAD

**Issue by davidhrbac** [ankane/blazer#174]
First of all, thanks a lot for the Blazer. Real lifesaver. :sunglasses: 

We are running blazer behind NGINX proxy. Blazer generates emails having links which point to `localhost` - https://localhost/admin/blazer/queries/15.

Is there a way to change the configuration to include base url?

**Comment by ankane** [comment]
Hey @davidhrbac, you likely need to configure your default ActionMailer host.

**Comment by davidhrbac** [comment]
@ankane sorry, to reply today. Yes it must be properly configured `config.action_mailer.default_url_options` in `config/environments/*`
