### ISSUE TITLE
Disable "New Dashboard", "New Check" and "New Query" in the UI

### ISSUE THREAD

**Issue by cg5544** [ankane/blazer#175]
We want our users to use the dashboard that we build using Blazer, but we DO NOT want to give them the ability to create new dashboard/check/query. How do we disable those so that they don't show up in the UI?

<img width="995" alt="blazer_new_actions_2017-10-25_2349" src="https://user-images.githubusercontent.com/5017304/32034236-67d474ae-b9df-11e7-851b-ccf03b36338f.png">

**Comment by ankane** [comment]
Hey @cg5544, Blazer does not currently have a permissions model.

**Comment by cg5544** [comment]
@ankane Okay thank you very much for your response.
