### ISSUE TITLE
Strange things with User class and I18n config

### ISSUE THREAD

**Issue by belovamarina** [ankane/blazer#176]
Hi! Thank you for great gem!
I'm new in RoR and got very strange bug after installing blazer. This is my code:

/config/application.rb

```ruby
require_relative 'boot'
 require 'rails/all'
 Bundler.require(*Rails.groups)
 
 module Flashcards
   class Application < Rails::Application
     config.load_defaults 5.1
     config.i18n.default_locale = :ru
     config.i18n.available_locales = [:ru, :en]
   end
 end
 ```
 
 /app/models/user.rb
 
 ```ruby
class User < ApplicationRecord
  rolify role_cname: 'Admin'
  before_create :set_default_locale
  before_validation :set_default_locale, on: :create

# ...
  validates :locale, presence: true,
                     inclusion: { in: I18n.available_locales.map(&:to_s),
                                  message: 'Выберите локаль из выпадающего списка.' }

  private

  def set_default_locale
    self.locale = I18n.locale.to_s
  end
end
```

If in blazer.yml I'm not commenting out user_class, I got validation error:
```
Blazer.user_class
 => User (call 'User.connection' to establish a connection)
 ```
```
u = User.create(email: "example@example.ru", password: "123456", password_confirmation: "123456", locale: "ru")
u.errors => ...
@messages={:locale=>["Выберите локаль из выпадающего списка."]}, @details={:locale=>[{:error=>:inclusion, :value=>"ru"}]}
```
And validator:
```
Blazer.user_class.validators => ... #<ActiveModel::Validations::InclusionValidator:0x007fca4b0a3f30 @attributes=[:locale], @options={:in=>["en"], :message=>"Выберите локаль из выпадающего списка."}, @delimiter=["en"]>
```
Otherwise, if in blazer.yml wrote:
`user_class: User`
All tests are green.
```
Blazer.user_class
   => "User"
```
I think maybe the reason that in first case Blazer calls User model before rails load config?
`  Blazer.user_class ||= Blazer.settings.key?("user_class") ? Blazer.settings["user_class"] : (User rescue nil)`
Thank you!

**Comment by ankane** [comment]
Hey @belovamarina, thanks for the detailed report 💯  I'll see if Blazer can determine the User class without loading the model in the engine initializer.

**Comment by ankane** [comment]
Can you see if the `fix_user_loading` branch fixes it?

**Comment by belovamarina** [comment]
@ankane  Yes, this branch fixes my issue with user class. Great solution, thank you!)

**Comment by ankane** [comment]
Whoops, forgot about this. Merged to master. Thanks @belovamarina for reporting and confirming the fix 👍
