### ISSUE TITLE
Blazer Cannot Save Queries In Apps using the "protected_attributes" gem.

### ISSUE THREAD

**Issue by brandonkboswell** [ankane/blazer#178]
For apps that started before Rails 4 and still use attr_accessible over Strong Parameters, Blazer Fails when saving queries (Can't mass-assign protected attributes for Blazer::Query: name, description, statement, data_source). 

Is there any known way to get around this?

**Comment by ankane** [comment]
Hey @brandonkboswell, you should be able to reopen the models and add `attr_accessible`. Try creating an initializer with:

```rb
Blazer::Query # preload model

class Blazer::Query
  attr_accessible :name, :description, :statement, :data_source
end
```

**Comment by brandonkboswell** [comment]
On first glance seems to work. 👍

**Comment by ankane** [comment]
Thanks for sharing. On a related note, here’s the low risk approach we took to upgrade to strong parameters: https://github.com/ankane/shorts/blob/master/Strong-Parameters.md
