### ISSUE TITLE
Support for variables that are already inside quotes

### ISSUE THREAD

**Issue by dwbutler** [ankane/blazer#179]
I'm trying to create a report with a variable that feeds into a statement `WHERE name ILIKE '%{keyword}%'`. (This is a Postgres database.) When I run the report with a variable value such as `health`, the generated query is `WHERE name ILIKE '%'health'%'`, which is a syntax error. Ideally, there would be some smart detection in place that would detect that the variable is already enclosed in quotes, and avoid double quoting.

**Comment by dwbutler** [comment]
I was able to solve my specific issue using Postgres full text search: `WHERE name @@ to_tsquery({keyword})`

**Comment by JayTeeSF** [comment]
I'm using mysql and would prefer not to require the user to know how-to wildcard their search input.
Being able to write `where name like '{search-input}%'` would help me (as DBA) to avoid letting admin-website-users type: '%search string%' and slowing down the server more than I'd like :)

**Comment by ankane** [comment]
FWIW you can also do `WHERE LIKE '%' || {var} || '%'` in Postgres.
