### ISSUE TITLE
Javascript breaks in queries/show

### ISSUE THREAD

**Issue by boudewijnv** [ankane/blazer#18]
After I save a simple query and then try to view it, it doesn't show any data. Instead it displayes 'loading...'. 

Reason is a breaking js error:

```Uncaught SyntaxError: Unexpected identifier```

Then on that line I see:
```
    $.post("/tt-queries/queries/run?subaccount=experience", {statement:select * from users limit 1,query_id:1}, function (data) {
```

Seems like the statement is missing quotes. 

We're using rails 4.0.13.

**Comment by ankane** [comment]
It's due to this issue with Rails 4.0. https://github.com/rails/rails/pull/6094
