### ISSUE TITLE
Feature Request: Pie Charts

### ISSUE THREAD

**Issue by cto-jean** [ankane/blazer#181]
Could you please add in support for pie charts?

**Comment by jaxn** [comment]
I would like to propose a way to do this:

Let the name of the numeric column provide a hint as to the chart to draw:
```
# pie chart
SELECT category, COUNT(*) AS pie FROM my_table GROUP BY 1

# line chart
SELECT category, COUNT(*) AS line FROM my_table GROUP BY 1

# bar chart
SELECT category, COUNT(*) AS bar FROM my_table GROUP BY 1

# area
SELECT category, COUNT(*) AS area FROM my_table GROUP BY 1

# column (default) 
SELECT category, COUNT(*) AS column FROM my_table GROUP BY 1 

# stacked column
SELECT category, subcategory, COUNT(*) AS stacked FROM my_table GROUP BY 1,2
```

If this looks like something @ankane would potentially accept, I will put together a pull request.

**Comment by cto-jean** [comment]
I am hoping to hear that this feature has been added soon!!  It seems like it would be useful to the entire community.  If there is a Patreon account or something I could throw some dinero into, I'd be happy to fund some munchies to the team.

**Comment by ankane** [comment]
Hey @cto-jean and @jaxn, thanks for the suggestions. I went ahead with the column name approach for pie charts. To keep things simple, I don't want to add any other chart types for now.
