### ISSUE TITLE
current_user not being used

### ISSUE THREAD

**Issue by StanBright** [ankane/blazer#185]
It may not be a real issue, but I can't figure it out what is happening. It is a Rails v5.1.4 app with blazer v1.8.0. I have *current_user* defined in the application_controller, and it returns a `User` instance.

I have uncommented the relevant options within blazer.yml, too:
```
# class name of the user model
user_class: User
# method name for the current user
user_method: current_user
# method name for the display name
user_name: username
```

The problem is that whenever I create a new query or edit something the user is not linked to those blazer records. Any idea what could be wrong?

**Comment by ankane** [comment]
Hey @StanBright, I haven't seen that before, but from the description, I don't think it's a Blazer issue. If you find strong evidence that it is, please reopen. Also, if you figured it out, it'd be great to leave a comment for future readers.
