### ISSUE TITLE
Read Only Database User

### ISSUE THREAD

**Issue by jrtowell** [ankane/blazer#19]
Dummy question...

The docs recommend making the database user a read-only user. How can the app save queries if the database user is read only?

**Comment by starchow** [comment]
@jrtowell When the app save queries, it use the normal connection (the default database connection). When the app run queries it use the read-only connection (BLAZER_DATABASE_URL). Therefore user can't not change the database when he run queries from Blazer.

**Comment by jrtowell** [comment]
Got it, thanks!
