### ISSUE TITLE
"Inline" Docs / Reminders of variable options

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#190]
It'd be cool if the query editor had a little table of the special formats/names that make variables work. Optionally, a separate page like the schema would work just fine too.

For example, my brain always tries to use `{start_date}` instead of `{start_time}`. I'm just imaging a table which lists who the variables would be displayed. And, I suppose you could also generate some entries from any smart variables added in the configuration (in case you might need to alias a column to `user_id` instead of something else.)

**Comment by ankane** [comment]
Hey @cycomachead, great idea. Adding this as part of Blazer 2. You can see what it looks like on the `2-0-dev` branch.
