### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sds-dubois** [ankane/blazer#191]
I installed the gem as suggested but the urls created by the url helper inside the Blazer engine are broken.

For example when going to `/blazer`, the "New Query" button points to 
```http://localhost:3000/blazer/assets?action=new&controller=blazer%2Fqueries```
I can manually go to `/blazer/queries/new`, the page renders well, but once again the form endpoint is broken so I'm not able to create a query.

When running `rails routes` I do see all the engine routes (and in particular `/queries/new`)
```
Routes for Blazer::Engine:
    ....
    new_query GET    /queries/new(.:format)            blazer/queries#new
    ....
```

Please let me know if I can help in any way or provide more info.

**Comment by ankane** [comment]
Hey @sds-dubois, thanks for reporting 👍 Are you able to reproduce with a fresh app?

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by archonic** [comment]
The same issue was described in #198 and I'm experiencing it as well. I created a fresh application and it worked. I also installed devise, introduced the devise auth constraint from the readme and wrapped the Blazer mount line in `namespace :admin do` and it all worked. I've so far been unable to reproduce in a fresh app but I'll keep working on it. @sds-dubois did you ever narrow this issue down?

**Comment by firdausmaarof** [comment]
i'm also facing the same issue. i cannot find where the `assets` in the url come from.

**Comment by BrianSigafoos** [comment]
@ankane I can confirm, seeing the same issue on Rails 6, ruby 2.7.1, blazer 2.3.1.
Tracked the issue down to this suggested fix:
https://stackoverflow.com/questions/42490350/rails-engine-routes-do-not-work-without-adding-the-engine-prefix#comment72127863_42490350

I can confirm that removing `include Rails.application.routes.url_helpers` from ApplicationHelper fixes the issue completely.

```
module ApplicationHelper
  # include Rails.application.routes.url_helpers
 ...
```

cc Other reporters of this issue: @firdausmaarof @archonic @sds-dubois  @badogar @badogar @Pazzik

**Comment by Pazzik** [comment]
@BrianSigafoos Thanks. It worked. how can we fix the blazer to prevent the problem? pg_hero works fine without having to change anything in my application

**Comment by Pazzik** [comment]
The problem was in `Blazer::BaseController < ApplicationController` When i replaced it with `Blazer::BaseController < ActionController::Base` everything fixed. @ankane can we add this as a fix to the blazer?

**Comment by Pazzik** [comment]
For those who have encountered a similar problem. My final solution This is to add these lines
```
module Blazer
  class ApplicationController < ActionController::Base
  end
end
```
 to `config/initializers/blazer.rb`

cc Other reporters of this issue: @firdausmaarof @archonic @sds-dubois @badogar @BrianSigafoos

**Comment by ankane** [comment]
Hey @BrianSigafoos and @Pazzik, thanks for sharing. Blazer inherits from `ApplicationController` so it can use authentication from it (since not all frameworks hook into `ActionController::Base`).

Out of curiosity, what's the use case for including URL helpers in `ApplicationHelper`? (haven't seen that pattern before)

**Comment by BrianSigafoos** [comment]
@ankane I agree URL helpers in Application Helper aren't needed. Removing from an old codebase fixed the issue for me.

If lots of other folks need them, blazer could prefix its routes in templates with `blazer`. 
Ex: `new_query_path` -> `blazer.new_query_path`. I believe that would also fix the issue.

**Comment by ankane** [comment]
@BrianSigafoos Can you give master a shot? From my testing, `clear_helpers` should fix it.

**Comment by BrianSigafoos** [comment]
@ankane Confirmed that `master` now fixes the issue, with `include Rails.application.routes.url_helpers` in `ApplicationHelper`. 🎉 🙏
