### ISSUE TITLE
Feature Request: manipulate data without explicitly writing SQL queries

### ISSUE THREAD

**Issue by BKSpurgeon** [ankane/blazer#193]
a series of drop downs a la ransack to choose and select data would be very helpful to those not knowing SQL.

**Comment by ankane** [comment]
Hey @BKSpurgeon, thanks for the idea 👍 This is pretty common among BI tools, but I’d prefer to keep Blazer SQL-based. I’ve found people can pick it up pretty quickly when they have example queries to look at.

**Comment by BKSpurgeon** [comment]
:+1:  chrs

**Comment by pedrocarmona** [comment]
I tried to implement it with just sql, and run into some problems:
- had to change blazer (selectize) to include multiple options (and always write queries with `column IN (?)` 
- allow null values, this was harder: made some ugly sql `case` statements

And in the end it was not so good to make PR :)
