### ISSUE TITLE
Open to adding RSpec tests?

### ISSUE THREAD

**Issue by acuppy** [ankane/blazer#194]
Not to hastily assume, but I noticed there was not an existing testbed in the code base.  I'm interested in helping backfill a few critical paths; starting with functional/integration tests and then moving onto unit tests.

I want to be of value, so would that be valuable? If so, objections to RSpec and Capybara?

This is an amazing tool, and having coverage might bring more certainty to the userbase and things evolve.

- Adam

**Comment by ankane** [comment]
Hey @acuppy, I appreciate the offer, and sorry for the delay. I use Minitest for my other projects, so that'd be preferred. If you're still interested, I'd start with something small, submit a PR, and we can discuss.
