### ISSUE TITLE
mapping ahoy visits?

### ISSUE THREAD

**Issue by skryking** [ankane/blazer#199]
Any chance there is a way to map ahoy visits in a query?  I see that to create a map we need long and lat, but the visits only provide city, country, region?  Is there something I should add to the ahoy configuration to get those? If this is the wrong place to ask let me know and I'll go ask someplace else.

**Comment by ankane** [comment]
Hey @skryking, mapping only works for latitude and longitude. There isn't a way to do it based on city or country strings.
