### ISSUE TITLE
Date bug?

### ISSUE THREAD

**Issue by shirkavand** [ankane/blazer#201]
Sorry for not posting this at Stackoverflow as the guide indicates. The thing is that i need a reputation of 1500 (which i do not have) in order to use the #blazer tag.

Hope you can help me with this.

I know that in order to use date ranges this needs to be done:

`date_attribute >= {start_time} and  date_attribute <= {end_time}.`

But what about if i do not need a date range only a date, something like:

`date_attribute <= {start_time}`

The sentence above does not show a data picker in the UX/UI, just a regular textfield with a date string inside.

Any idea?

Thanks

**Comment by ankane** [comment]
Hey @shirkavand, this is intended. The range picker only shows up when both start_time and end_time are specified.

**Comment by feliperaul** [comment]
@ankane I agree with @shirkavand here, I also thought this was a bug ... is there an indented UX reason for not showing a regular date picker in this case, or that could be an enhancement / feature request?

**Comment by ankane** [comment]
I can see how it's a bit odd now. Just fixed as part of the upcoming 2.0 release.
