### ISSUE TITLE
[Idea] Display single value metrics in dashboard

### ISSUE THREAD

**Issue by markphip** [ankane/blazer#204]
FWIW, StackOverflow does not show Blazer as a valid tag so posting here.

We like the dashboard and the charts etc. but we also want to be able to display various single value metrics.  Things like total customers, average sales price, MRR etc.  Creating the queries for these are easy but it is less clear from the examples what the options are for displaying things like this on the dashboard.

While a graph of how many customers added per week over the last 12 months makes a nice graph, there is still a desire to display basic single number metrics like we have N active customers.

**Comment by markphip** [comment]
I guess I was wondering about the visualization and whether it could be made to look pretty.  Something like this mockup:  https://bootsnipp.com/snippets/featured/hero-widgets

**Comment by ankane** [comment]
TBH I like the way it is now.
