### ISSUE TITLE
Chart limited to 20 columns

### ISSUE THREAD

**Issue by electricowl** [ankane/blazer#206]
Apologies if this has been answered elsewhere but I can't find it.

I created a query to run over a period of 30 days and as expected the date runs on the x-axis and the bars are rendered correctly. 

However, only 20 columns are displayed in spite of there being 30 dates to display.

Is there a configuration option for this?

`SELECT CAST(report_date AS VarChar) report_date, SUM(units)  FROM "c_logs" WHERE cl_code = 'xxx' AND vendor = 'yyy' AND status = 4 AND (NOW()::date - report_date::date) < 32`

![image](https://user-images.githubusercontent.com/650952/44960984-0a73f600-af01-11e8-946d-eb6a6921755c.png)

Many thanks.

**Comment by ankane** [comment]
Hey @electricowl, had to draw the line somewhere, so decided on 20. There's not an option for it.

**Comment by electricowl** [comment]
Thanks for the response @ankane 

Blazer is amazing, powerful and incredibly easy to set up with Chartkit. I can appreciate the need to draw the line in certain places. I'll work around/with the first 20 rule. 

Many thanks.
Ian
