### ISSUE TITLE
[Idea] Do not require "eval" for MongoDB

### ISSUE THREAD

**Issue by 1I1III1liL1** [ankane/blazer#212]
`eval` is generally considered unsafe for MongoDB, put it [seems to be](https://github.com/ankane/blazer/blob/4b1212bdb51e0c6b3fd4fff3a0a8bd0deea28eeb/lib/blazer/adapters/mongodb_adapter.rb#L10) how Blazer issues commands to MongoDB.

Since the user is supposed to be readonly, would it be possible to execute the query as-is?

**Comment by ankane** [comment]
Hey @1I1III1liL1, can you give an example of how Blazer would "execute the query as-is"?

**Comment by gsdean** [comment]
Not sure what's going to happen, but it seems something will eventually need to change.

Adding this for reference...

From https://docs.mongodb.com/manual/reference/method/db.eval/
> Starting in version 4.2, MongoDB removes the eval command. The deprecated db.eval(), which wraps the eval command, can only be run against MongoDB 4.0 or earlier versions. For behavior and example, refer to the 4.0 or earlier version of the manual.
