### ISSUE TITLE
Time series with null values

### ISSUE THREAD

**Issue by feliperaul** [ankane/blazer#213]
Hi Ankane! Your gems are the best :)

I'm copying and pasting the SQL generated on Rails console with ActiveRecord to use with blazer and it has been working fine. 

Having said that, using your great gem `groupdate`, I'm running some nice queries grouped by day, week or month.

Let's ay I'm grouping by day. Some of my queries return a series that have no value for some days (for instance, the count or sum is 0). 

In your gem, I see the results return a value for each day of the series (with 0 on them), unless I pass `series: false`; in this case I get back only results that have data (count exists). 

But since the SQL query is the same, I'm wondering how I could replicate this 'series' behavior in Blazer.

Let's say I have 10 sales one day, 0 sales the next day, and 10 sales the following day. The plotted graph will trace a straight line between this two data points, when in reality it should drop to 0 and then come back to 10.

I hope I could make myself understood, because the graphs being generated are a bit misleading as of now. Cheers!

**Comment by feliperaul** [comment]
Take a look at this image:

![image](https://user-images.githubusercontent.com/743879/46723678-c0dca080-cc4e-11e8-9187-36516d597a13.png)

After august 5, we expected the graph to drop to 0, but it doesn't, tracing a straight line to the next data point. Even tough the graph is smart to add 'space' between them (because there are many days between them, even tough they are 2 consecutive data points), the straight line is misleading, because in reality we have 0 between those two data points.

**Comment by feliperaul** [comment]
@ankane thank you!

**Comment by kyleschmolze** [comment]
Ok, this was very tricky for me to get working, but I did, so I figured I'd post some code here for the next person who needs this!

For daily queries, you can tell the `GENERATE_SERIES` to just start on any specific day like `2022-01-01`. But if you are doing weekly or monthly queries, you need to make sure you generate the same (truncated) dates in your series. If your `GENERATE_SERIES` is 1 day per month on the 15th of each month, but the `DATE_TRUNC` tries to group your data into the 1st of each month, you'll get no data. So the way to fix that is to just use `DATE_TRUNC` in the `GENERATE_SERIES` as well!

```
    SELECT general_date.date AS date

           , COUNT(listings) AS count

       FROM (
            SELECT GENERATE_SERIES(
                DATE_TRUNC(
                    'month', 
                    (CURRENT_DATE - interval '12 months')::timestamptz 
                    AT TIME ZONE 'Etc/UTC'
                ),
                CURRENT_DATE, '1 month')::DATE AS date
        ) AS general_date

       LEFT JOIN listings

       ON DATE_TRUNC('month', "listings"."created_at"::timestamptz AT TIME ZONE 'Etc/UTC')::date = general_date.date
       GROUP BY 1
       ORDER BY 1
```

Works for me!
