### ISSUE TITLE
Not able to connect Blazer to Staging DB

### ISSUE THREAD

**Issue by vasudharsai** [ankane/blazer#215]
I created databse_url for staging as mysql2://root:password@local_host:3306/database_name_staging
After deploying it to staging and when I try to run any query I get the below error:

URI::InvalidURIError (the scheme mysql2 does not accept registry part: root:password@local_host:3306 (or bad hostname?)):

**Comment by ankane** [comment]
Hey @vasudharsai, the URL is invalid, as the error states

**Comment by vasudharsai** [comment]
The documentation states the URL should be in the below format: 
url: mysql2://user:password@hostname:3306/database

I created the URL in the same format and still it doesn't work. I pinged the host and I got the acknowledgment. I ssh into the Staging server and was able to login to mysql console using the credentials in the url I defined. 

The URL looks similar to this:
"'mysql2://f77_oe_8_staging:LcCh%c467%768&^;kG9yG?JquGMK@factory77-aurora-staging-cluster.cluster-cmj74hfj67yjkjl.us-east-1.rds.amazonaws.com/factory77_oe_8_staging' "

Please advice

**Comment by vasudharsai** [comment]
> Hey @vasudharsai, the URL is invalid, as the error states
The documentation states the URL should be in the below format:
url: mysql2://user:password@hostname:3306/database

I created the URL in the same format and still it doesn't work. I pinged the host and I got the acknowledgment. I ssh into the Staging server and was able to login to mysql console using the credentials in the url I defined.

The URL looks similar to this:
'mysql2://f77_oe_8_staging:LcCh%c467%768&^;kG9yG?JquGMK@factory77-aurora-staging-cluster.cluster-cmj74hfj67yjkjl.us-east-1.rds.amazonaws.com/factory77_oe_8_staging'

Please advice
