### ISSUE TITLE
embed dashboard view in main app

### ISSUE THREAD

**Issue by francescob** [ankane/blazer#219]
Hello, I'm using your project and it's working very well, now I would like to embed the dashboard view in a partial inside my main app, is it possibile to do so?
Thanks

**Comment by ankane** [comment]
Hey @francescob, Blazer doesn't support this.

**Comment by andrew-newell** [comment]
For future readers, here's a gist where @jules2689 got embedding to work https://gist.github.com/jules2689/e0a90e0c58cea52969e531a60d0915e4

**Comment by jules2689** [comment]
I think we can close this one out @ankane ? 😄

**Comment by ankane** [comment]
Thanks for sharing @andrew-newell and @jules2689!
