### ISSUE TITLE
Timestamps display wrong time zone for Snowflake

### ISSUE THREAD

**Issue by dbechrd** [ankane/blazer#225]
I'm running a very simple query in blazer:

    select created_at
    from my_table
    where id = 12345

When I run this against `main` postgres database, it displays:

    2019-01-08 16:41:56 -0800

When I run the same query against `snowflake`, it displays:

    2019-01-09 00:41:56 -0800

I have verified via Snowflake console that this is a TIMESTAMP_NTZ(9) column and the output in console is `2019-01-09 00:41:56.078`. I'm pretty sure Blazer is erroneously adding the `-0800` timestamp specifier to a UTC timestamp. Does that seem like a viable cause?

**Comment by dbechrd** [comment]
We confirmed via Snowflake console that the the timestamp is UTC and that Blazer is interpreting it incorrectly. It's worth noting that while this shouldn't affect filter clauses, it does persist when you download the output as a CSV. @righi is investigating this as well. I would urge anyone reading this in the meantime to be wary of using timestamps generated by Blazer output for any official purposes without careful validation.

**Comment by ankane** [comment]
Just to clarify: TIMESTAMP_NTZ (by definition) don't have a time zone, so each database adapter interprets them how they'd like. Rails configures ActiveRecord to treat them as UTC by default. My hunch is the `odbc` ActiveRecord adapter is treating them as local time. You'll need to use the ActiveRecord adapter, not the Snowflake console, to check this.

**Comment by dbechrd** [comment]
Thanks for the clarification Andrew, appreciate the help!

**Comment by ankane** [comment]
Cleaning up issues. Feel free to add new information if you end up debugging
