### ISSUE TITLE
Query Won't Run If Variable Dropdown Is Left Blank

### ISSUE THREAD

**Issue by dorkrawk** [ankane/blazer#23]
Now that queries auto-submit when a value from a variable dropdown is changed, queries don't seem to run if one of those values is left unselected. Previously, unselected values were used to indicate that those values should be NULL.

**Comment by ankane** [comment]
Hey Dave, can you give an example query?

**Comment by dorkrawk** [comment]
Sure.  This is a good example: https://admin.instacart.com/admin/blazer/queries/5207-deliverylogs-by-warehouse-and-time-range-all-reconciliation-errors?warehouse_location_id=&start_time=2015-08-01T07%3A00%3A00%2B00%3A00&end_time=2015-09-01T06%3A59%3A59%2B00%3A00

It was previously used to show all warehouse locations by leaving the warehouse_locations_id dropdown unselected and then they would change the date range, and re-submit the query. Now the query can't be resubmitted just by changing the date range.
