### ISSUE TITLE
Line graph not working with concat function

### ISSUE THREAD

**Issue by muhammadumarkhan** [ankane/blazer#230]
Hi,

I am using concat function in my query to use '$' sign with fee. The problem I am facing is line graph is rendering without concat function but not working with concat.
Here is my query.

**With concat:**
```
select date_trunc('month', (bookings.created_at)::timestamp)::date as dt,
concat('$', avg(bookings.total_fee_usd)) as total_rent
from bookings
where bookings.state in ('paid_in_full')
group by dt order by dt desc
```
**Without concat**
```
select date_trunc('month', (bookings.created_at)::timestamp)::date as dt,
avg(bookings.total_fee_usd) as total_rent
from bookings
where bookings.state in ('paid_in_full')
group by dt order by dt desc
```
I want line graph and dollar sign as well. Help needed :)

Thanks!

**Comment by ankane** [comment]
Hey @muhammadumarkhan, check out docs for how data types work for charts.

**Comment by muhammadumarkhan** [comment]
Hi @ankane 
Can you please point out the place where is mentioned in the doc. We want to add a dollar symbol and display the line graph as well. We are using Postgres.

**Comment by muhammadumarkhan** [comment]
@ankane Is it possible for you to help me on this.
