### ISSUE TITLE
Athena Adapter - client_request_token hash does not allow you to run same query multiple times

### ISSUE THREAD

**Issue by preetsethi** [ankane/blazer#234]
Before I say anything else: wanted to say thanks to @ankane and all the other contributors for all the hard work on this library, it's kick ass!

I've uncovered some interesting behavior between Athena and the Blazer AthenaAdapter.
https://github.com/ankane/blazer/blob/master/lib/blazer/adapters/athena_adapter.rb#L16
```ruby
client.start_query_execution(
  query_string: statement,
  # use token so we fetch cached results after query is run
  client_request_token: Digest::MD5.hexdigest(statement),
  query_execution_context: {
    database: database,
  },
  result_configuration: {
    output_location: settings["output_location"]
  }
)
```

Using `client_request_token: Digest::MD5.hexdigest(statement)` is a smooth solution to track / fetch query results. 

However, only using `statement` as an input to the hash is causing issues. 

I believe this is because `client_request_token` is unique at the account level in Athena. There's not a lot of details on the scope but here's the relevant section of the docs:
https://docs.aws.amazon.com/athena/latest/APIReference/API_StartQueryExecution.html#API_StartQueryExecution_RequestSyntax
```
ClientRequestToken
  A unique case-sensitive string used to ensure the request to create the query is idempotent (executes only once). 
  If another StartQueryExecution request is received, the same response is returned and another query is not created.
  If a parameter has changed, for example, the QueryString, an error is returned.
```

This problem is two fold:
1. I have the same tables with the same names across two Athena / Glue databases. I set up two data sources in Blazer, one for each database. I'm able to run the statement on one data source / database, but when I try to run the statement on the second data source / database, I get the following error:`Idempotent parameters do not match`. **This is particularly annoying when trying to preview tables.** Going back to the AWS documentation, you'll see this line: `If a parameter has changed, for example, the QueryString, an error is returned.` Since the `client_request_token` across the two data sources is the same but the `query_execution_context: {database: database}` has changed, it throws the `Idempotent parameters` error.

Solution: 
Add `database` as an input to the hash. The `client_request_token` hash must factor in the `database`. 
-or-
Ensure the preview table statement uses the fully qualified database name in the query itself. Ex: `select * from 'database'.table` vs `select * from table`. 
In either case, this one seems pretty straightforward, pretty clean.

2. Even if we ignore my specific problem regarding two database with the same table names, there's still an issue with the unbound scope of the hash with respect to time. Let's assume you have a table. Assume you run a query. Let's assume you add a partition to said table. The expectation is that running the query again should return updated results with the new partition accounted for. However, since the hash is exclusively based on the `statement`, you get stale query results.

Solution: Add an input to the hash that references some period of time. 
**This one is not so straightforward**. 
In my case, I am fine with an hourly period. I could do something like: `DateTime.now.strftime("%Y%m%d%H")` as an input to the hash. 
My table crawlers run at the end of every hour and add new partitions. As local time moves into the next hour, I would be able to re-run the query and get updated results.

Clearly, this solution is really specific to my setup. In terms of a generalized solution, there's a whole slew of issues here. We would probably want to account for time zones? The period should probably be adjustable?

I'd love some input on how to generalize this so we serve the needs of the greatest number of folks.

I'd be more than happy to fork and test changes, then contribute. Definitely want some input from the community before that though.

And as always, if I've missed some detail, anyone please feel free to share!

Edit: Wanted to comment on the idea of adding time bounding in the query itself. Adding a where clause with variables like `created_at >= {start_time} and created_at <= {end_time}` for example, that would obviously solve the time bounding problem at the query level. While that obviously creates a unique query, this still would suffer from stale results for the same time period. Seems like there's a better solution.

**Comment by ankane** [comment]
Hey @preetsethi, thanks for the suggestions.

1. Sounds easy enough. We should probably use the data source id.
2. Ideally, this would work similar to how caching works now (where there is a set period, but you can force a refresh). Since this isn't really straightforward and Athena probably isn't a popular data store for Blazer, I don't want to spend time on this one. You can create a custom adapter for your app that extends the Athena adapter with the logic mentioned above.

**Comment by preetsethi** [comment]
@ankane 
1. Sounds good, would love to help out and contribute. I'll submit a PR for this soon. Will use data source id as you asked.
2. Your thoughts on a custom adapter for our Athena use case: great advice and I will definitely revisit this idea should the need arise. But yes, after more thought, realized the specificity to this problem comes from our ETL architecture and Athena itself. We're gonna revisit and look at this problem from that perspective. Shouldn't need to change your software to take care of this.

Expect a PR in a bit! Appreciate the help, thanks for the quick answer!
