### ISSUE TITLE
Getting Error while adding devise code to get admin access

### ISSUE THREAD

**Issue by DhanashreeDorage** [ankane/blazer#241]
Hello Ankane,

I am using devise, rolify and administrate gem to get admin access. When I added below devise code in route.rb file

authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
end

I get below error, 

undefined method `admin?' for #<User:0x00007f64e8f537b0>

Can you please help me to handle this?

**Comment by ankane** [comment]
Hey @DhanashreeDorage, please check out the Contributing Guide for where to help with code.
