### ISSUE TITLE
Blazer doesn't use the yield of application layout file?

### ISSUE THREAD

**Issue by Pacn91** [ankane/blazer#248]
Hi, first of all, thank you for this library. 

I've just started using it but I encountered a problem. When I access the blazer page I notice that the content of the blazer is not being inserted on the `yield` on my application layout file. Is this correct? And if so, how can I change this behavior? 

I'll much appreciate your help. Best regards!

**Comment by ankane** [comment]
Hey @Pacn91, Blazer uses its own layout. There's not an official way to have it use a different one (although if you check out the code, you can probably find a way).
