### ISSUE TITLE
rails g blazer:install looking for blazer.yml

### ISSUE THREAD

**Issue by djburdick** [ankane/blazer#25]
The install process is looking for the blazer.yml file before it exists: /lib/blazer.rb:26

Repro: Run ```rails g blazer:install``` without the config/blazer.yml file

```
/Users/dj/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/blazer-1.0.1/lib/blazer.rb:26:in `read': No such file or directory - /Users/dj/Code/getfixed/config/blazer.yml (Errno::ENOENT)
	from /Users/dj/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/blazer-1.0.1/lib/blazer.rb:26:in `settings'
```

Easy work around, but not ideal so thought you guys should know. Project looks cool btw!

**Comment by ankane** [comment]
Thanks @djburdick - important fix.
