### ISSUE TITLE
[Idea] Provide convenient permission hooks

### ISSUE THREAD

**Issue by stephendolan** [ankane/blazer#250]
Thanks so much for this gem. It's a game-changer in terms of providing custom reports to users.

I've got the access to the dashboard covered through the well-documented [Authentication](https://github.com/ankane/blazer#authentication) section, but what I'd like to do is use my existing `Role` model or `Pundit` policies to define who has access to which reports.

For example, one of the reports that an HR role needs contains the birth year of users. I want management to be able to pull and basic product data ad-hoc as well, but can't let them pull birth years of users.

I haven't looked into how this would/could be implemented, but wanted to run it by you here first to get your thoughts.

**Comment by ankane** [comment]
Hey @stephendolan, it's not documented, but there's an experimental `query_viewable` method for this. Here's how I've used it:

1. Create multiple sets of shielded views with [Hypershield](https://github.com/ankane/hypershield) - one for each role (normal users, hr, admins, etc)
2. Set up multiple data sources in Blazer - one for each role above (`primary`, `primary_hr`, `primary_admin`)
3. Use the `query_viewable` method to configure access

```ruby
Blazer.query_viewable = lambda do |query, user|
  case query.data_source
  when "primary_admin"
    user.admin?
  when "primary_hr"
    user.hr?
  when "primary"
    true # all users
  else
    false # default to false
  end
end
```

**Comment by ankane** [comment]
Cleaning up issues
