### ISSUE TITLE
Athena Adapter - some queries incorrectly return 0 rows

### ISSUE THREAD

**Issue by preetsethi** [ankane/blazer#252]
### Problem
Specifically in the case of:
```
MSCK REPAIR TABLE example_table;
```
Was returning zero rows even in cases I was sure we just dropped fat logs.

Diving into the Athena Client response:
```
#<struct Aws::Athena::Types::GetQueryResultsOutput update_count=nil, result_set=
  #<struct Aws::Athena::Types::ResultSet rows=[
    #<struct Aws::Athena::Types::Row data=[
      #<struct Aws::Athena::Types::Datum var_char_value="Partitions not in metastore:\texample_partitioned_table:2019/08/07/14">
    ]>
  ], result_set_metadata=#<struct Aws::Athena::Types::ResultSetMetadata column_info=[]>>, next_token=nil>
```

In `AthenaAdapter`: 
When processing the result, problematic assumption here:
```
column_info = resp.result_set.result_set_metadata.column_info
```
Column info is not always present.

Thus, the initial index is off:
```
rows = untyped_rows[1..-1] || []
```
Zero index is in fact relevant data in this case.

### Solution
Plan to pivot on the presence of column_info and handle appropriately from there.
I'll submit a PR.

### Question
Do I add generic column names? Column 1, Column 2, Column 3, etc

**Comment by ankane** [comment]
Re column names: I'd see how empty string looks.

**Comment by preetsethi** [comment]
Screenshot of output post PR:
<img width="926" alt="Screen Shot 2019-08-07 at 10 44 26 PM" src="https://user-images.githubusercontent.com/8645918/62678098-575c1a00-b965-11e9-9d24-a443e02b2f3f.png">
Pardon the blackouts.
