### ISSUE TITLE
Athena Adapter + Slack - `Query has not yet finished. Current state: QUEUED`

### ISSUE THREAD

**Issue by preetsethi** [ankane/blazer#253]
### Background
My experience with Blazer+Slack integration: excellent. 

In regards to Athena specifically, seeing this quite a bit (understandably so):
<img width="527" alt="Screen Shot 2019-08-07 at 10 20 20 AM" src="https://user-images.githubusercontent.com/8645918/62643699-660ee680-b8fd-11e9-8903-72d41370885f.png">

Checks firing off Slack messages in the middle of the night for Athena queuing is going to annoy the shit out of me.

Here's the block from `AthenaAdapter`:
```
query_execution_id = resp.query_execution_id

timeout = data_source.timeout || 300
stop_at = Time.now + timeout
resp = nil

begin
  resp = client.get_query_results(
    query_execution_id: query_execution_id
  )
rescue Aws::Athena::Errors::InvalidRequestException => e
  if e.message != "Query has not yet finished. Current state: RUNNING"
    raise e
  end
  if Time.now < stop_at
    sleep(3)
    retry
  end
end
```

### Proposed Solution
1. Loosen the conditional so that we mute both the `RUNNING` and `QUEUED` exceptions. 
2. Make sleep timer configurable via a setting (so that I can double or triple the wait... the size of our partitions / tables overall necessitates that).

**Comment by ankane** [comment]
Hey @preetsethi, happy to accept a PR to retry in the QUEUED case. You can already control the time with the `timeout` option.
