### ISSUE TITLE
Athena Adapter - client_request_token and caching

### ISSUE THREAD

**Issue by preetsethi** [ankane/blazer#254]
I raised a lot of these issues in #234. At the time, I didn't have a great solution.

However, as I have spent more time dealing with the problem:  the Athena adapter, in a few specific but common cases, is nearly unusable without some type of cache expiration for this token. 

Common use case: you have a dashboard query that you check periodically, which runs aggregates on time series data. Blazer makes it soo easy to turn this into a pretty chart too.
With Kinesis+Athena, you're doing date-time-based partitions and attaching incoming data as partitions.

The current hashing factors that produce the lookup token: it basically means I'm getting the cached results from when I wrote the query a week ago. I have to change the query in arbitrary ways like switch order direction... or even worse, add extraneous fields like dates or random strings, to generate a new `client_request_token`.

There must be a cache expiration mechanism for any given query, even if its a day, week, month, year, whatever.

I will have my proposal up for you as a PR in a few days. While I sense there will be objections to the manner in which I allow configurability, but I beg of you, we must add some sensible cache expiration factor to the `client_request_token` hashing mechanism.

To be continued ...

**Comment by ankane** [comment]
Hey @preetsethi, as I mentioned in #234, I think your best bet is to create a custom adapter that inherits from the existing one. If it turns out to be useful / generalizable after a few months of use, happy to consider a PR.

**Comment by preetsethi** [comment]
@ankane 
I appreciate the speedy response! Moreover, I appreciate the caution, always wise.
Still wanted to share the PR, while it's fresh on the mind.

I'm going to be running this in prod for the foreseeable future, will report back. Initial assessment: resolves our issues, offers configurability for various cases.

As always, appreciate the time and any future input. 
Thanks for your hard work man. We use Blazer and Chartkick everyday. Major thanks.

**Comment by ankane** [comment]
Thanks for sharing. I think the ideal setup would to remove caching on Athena (use a random `client_request_token`) and use the caching in Blazer: https://github.com/ankane/blazer#caching. This would allow you to force a refresh at any time.

The reason this isn't the default is Athena can get expensive if you don't set this up properly.

**Comment by preetsethi** [comment]
@ankane 
Blazer's caching was the muse / what I was going for with this approach, which I am now realizing was perhaps misguided: having two caching configs, figuring out which one is responsible in what cases, etc etc. Unique/random `client_request_token` + Blazer's caching would be ideal: DRY things up in terms of caching config.

I think your concern regarding the default and cost with Athena could be alleviated similarly to your warnings about setting up a read-only user: https://github.com/ankane/blazer#permissions
You make your recommendation clear and warn users multiple times in the docs. It's the user's responsibility to take your advice.
 
I think a similar approach with Athena could be taken with the following docs: https://docs.aws.amazon.com/athena/latest/ug/workgroups-setting-control-limits-cloudwatch.html

Check out the end of this blog post (section titled "Managing query usage and cost"):
https://aws.amazon.com/blogs/big-data/separating-queries-and-managing-costs-using-amazon-athena-workgroups/

In the same spirit of your _read-only_ user, creating an _audited_ workgroup in Athena with usage / cost controls should be a similar safety measure taken. 

Granted, you wrap RDBMS queries in transactions and rollback, a true failsafe.
The difference here is that you are depending on the user to enact their own failsafe, making the possibility of shooting themselves in the foot much more likely.

I understand your concerns when looking at this in a generalized approach, as you have to, being the maintainer of this project. 
But in my case, the interactions in the default Blazer config were problematic when we add partitions hourly and our BI users wanted to monitor at least that closely. Telling them 'just change the query: add a random string to your SELECT or change the ORDER direction' ... I got tired of the dirty looks. 

Perhaps this might be the best approach:
- Current logic for `client_request_token` remains default
- AthenaAdapter accepts a setting: `disable_athena_caching` or something like that, maybe `enable_blazer_caching`... open to suggestions here. Maybe more direct: `randomize_client_request_token`?
- If setting enabled, `client_request_token` is randomized.

If you want me to tackle any of this, let me know which approach you like and I can take care of it, get you and updated PR ASAP. I'll make sure to clarify recommendations / best practices with Athena in the documentation and link to the AWS docs.

If you'd like to leave it as is, consider this resolved and close.

Regardless, thanks once again for Blazer / Chartkick / Groupdate and thanks for your time here with my concerns. Appreciate it.

**Comment by ankane** [comment]
We can probably use a random token if the caching mode is `all` and update the docs to say Athena queries are cached forever by default, unless you specify caching in Blazer. What do you think?

**Comment by preetsethi** [comment]
I'll work on this and get back to you sometime next week! Thanks man.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to submit a PR if you're still interested in this feature

**Comment by preetsethi** [comment]
@ankane 
Sorry for the delay. I rolled out the code in https://github.com/ankane/blazer/pull/255 for our production use case, which has proved sufficient for us.

As is the nature of open-source contributions (in your personal time), I sadly never got around to this. I appreciate you closing out the issue. I'm also going to close out the PR as I think it's a little hacky (but works for us haha). 

Regardless, I appreciate your open source contributions and your attention to this issue! Thank you sir!

**Comment by jdelStrother** [comment]
> Thanks for sharing. I think the ideal setup would to remove caching on Athena (use a random `client_request_token`) and use the caching in Blazer: https://github.com/ankane/blazer#caching. This would allow you to force a refresh at any time.
> 
> The reason this isn't the default is Athena can get expensive if you don't set this up properly.

FWIW, the aws sdk generates a random token for you, in Aws::Plugins::IdempotencyToken. That only helps with internal retries (rather than the caching effect that Blazer's client_request_token is trying to achieve), but would mean that Blazer just specifying a random token would be somewhat redundant.

It took me quite a while to figure out why our Athena-based charts weren't refreshing properly - this seemed a surprising default behaviour to me.
