### ISSUE TITLE
Database URL is invalid if the password has the symbols in it.

### ISSUE THREAD

**Issue by ACPK** [ankane/blazer#259]
When I tried a password that has symbols in it, Blazer says the URL becomes invalid. However, it's no longer valid (though the password is now incorrect) if I remove those the symbols (ex: %%).

**Comment by ankane** [comment]
Hey @ACPK, special characters must be percent-encoded like with `psql`.

**Comment by ACPK** [comment]
@ankane Thank you for your help!
