### ISSUE TITLE
JS error when loading charts after saving

### ISSUE THREAD

**Issue by djburdick** [ankane/blazer#26]
The chart preview screen is working, but after saving and trying to load the charts I get this JS error and the chart doesn't load:
<img width="1191" alt="screenshot 2015-10-09 16 57 28" src="https://cloud.githubusercontent.com/assets/209698/10407940/1c7027d6-6ea7-11e5-831e-48552f37e66a.png">

If the SQL query is put in single quotes (eg: ```'select created_at, count(*) from user_tickets GROUP BY YEAR(created_at), MONTH(created_at)'```) it fixes this error (but messes up the preview page since it tries to execute the quotes).

**Comment by ankane** [comment]
What version of Rails are you on? There's a known issue with 4.0 - see #18 for details

**Comment by djburdick** [comment]
Gottcha. I'm on Rails 4.0. I created a pull request that fixes this issue (adds the Rails 4.1 change) so you can support Rails 4.0 if you want.

**Comment by ankane** [comment]
Fixed with #29
