### ISSUE TITLE
Blazer's "Preview Table" is blank for AWS Redshift

### ISSUE THREAD

**Issue by ACPK** [ankane/blazer#261]
After successfully connecting to a Redshift database, I found that the "Preview Table" is blank. We use Segment.com for analytics which created a separate schema for every data source (ex: SELECT * FROM mailchimp.campaigns). 

Do you have any suggestions on how to preview the schemas and related tables when using Redshift?

**Comment by ankane** [comment]
Hey @ACPK, one reason it could be blank is the database user doesn't have permission to view any tables. I'd confirm you can run queries like `SELECT * FROM mailchimp.campaigns` through Blazer successfully.

**Comment by ACPK** [comment]
@ankane - Yes, the query `SELECT * FROM mailchimp.campaigns` works correctly in Blazer.

**Comment by ankane** [comment]
Hey @ACPK, I still think it's probably a permissions issue. Try turning on Active Record logging, finding the query that's run to get the get the table list (should include `information_schema.tables`), and running that query in Blazer.
