### ISSUE TITLE
How do you do a multi-query?

### ISSUE THREAD

**Issue by jasonperrone** [ankane/blazer#262]
Can I not run a multiple query?
select count(*) from users;
select count(*) from roles;

OR
select count(*) from users 
/
select count(*) from roles

OR 
select count(*) from users
GO
select count(*) from roles
GO

?

**Comment by jasonperrone** [comment]
And just to be clear what I am really trying to do:
create temp table;
select into temp table;
select more stuff into temp table;
select * from temp table <-- my actual displayed results.

**Comment by ankane** [comment]
Hey @jasonperrone, queries can only be a single statement. You can achieve what you want on many relational databases with a common table expression or similar. Postgres example: https://www.postgresql.org/docs/current/queries-with.html

**Comment by jasonperrone** [comment]
Yep, thanks man, I figured it out with aliased tables and subselects. All good here.
