### ISSUE TITLE
JS and HTML are being escaped and displayed on the page

### ISSUE THREAD

**Issue by fedegl** [ankane/blazer#263]
I just did a clean install of Ahoy and Blazer on a Rails 6.0 app. And there seems to be some issue with Javascript and HTML being improperly escaped instead of being interpreted.

<img width="1209" alt="Screen Shot 2019-10-20 at 11 24 51 PM" src="https://user-images.githubusercontent.com/17049/67174727-2cdd0300-f391-11e9-954d-1bee047a2547.png">

I tried different queries and they all had the same problem.

Thanks for the great set of gems! It was a breeze to install!

**Comment by fedegl** [comment]
it got fixed somehow, I thought is might have been related to using the `turbolinks_render` gem but it was a false flag.

**Comment by devadmin-apto** [comment]
I am seeing exactly the same problem.  Clean install of ahoy and Blazer on a Rails 6.0 app

**Comment by mbjornson** [comment]
I'm seeing this as well on a new ahoy and blazer install, also Rails 6.
