### ISSUE TITLE
Error compiling assets.

### ISSUE THREAD

**Issue by alextakitani** [ankane/blazer#265]
Selectize depends on microplugin.js that breaks when minified by Rails 4.2

The error is:

Uncaught SyntaxError: Invalid Unicode escape sequence

I've made a fork and loaded it from a cdn and its working fine.

**Comment by ankane** [comment]
Hey @alextakitani, thanks for reporting. Rails 4.2 is no longer supported, but feel free to link to your fork so other that come across this can use it.

**Comment by khataev** [comment]
Active admin does not require sprockets anymore proof: https://activeadmin.info/0-installation.html 

```
webpacker
For new apps starting with Rails 6.0, Webpacker has become the default asset generator. You can opt-in to using Webpacker for ActiveAdmin assets as well by updating your configuration to turn on the use_webpacker option, either at installation time or manually.
```
I just have such application with AA and webpacker only and wanted to use blazer, but it was a bummer (((
