### ISSUE TITLE
bar or pie chart from data

### ISSUE THREAD

**Issue by BluGeni** [ankane/blazer#266]
Is there a way to get a bar graph or pie chart from this:

SELECT SUM(original_size) / 100000 as "MB Uploaded", SUM(compressed_size) / 100000 as "MB Compressed", COUNT(*) as pie
FROM uploads

I would like to show the original_size in comparison to the compressed_size visual.

**Comment by ankane** [comment]
Hey @BluGeni, you'll need to get the data in one of the supported chart formats. Check out the readme or Docs link in your Blazer installation for details.
