### ISSUE TITLE
Generic error and how to fix it

### ISSUE THREAD

**Issue by coliveiraluca** [ankane/blazer#267]
Hi,

I'm using the gem for database consults on a system, locally it worked just fine and I was able to create queries.

But now I have it in a system running in production but cannot make any querries. It's connected to the database, it shows the schema. But whenever I try to make a simple such as ```SELECT * FROM``` it returns me an error with "Not acceptable".

How do I proceed with this error? What's the probable cause of it? 
Thanks!

**Comment by ankane** [comment]
Hey @coliveiraluca, I've never seen that error before. Can you paste the full query, error message, and data store you're using?

**Comment by ankane** [comment]
Closing due to no response
