### ISSUE TITLE
Let Blazer play nice with Lockbox

### ISSUE THREAD

**Issue by bo-oz** [ankane/blazer#269]
Hi,

Is there a way to let blazer play nice with Lockbox? I'd like to see the unencrypted values for some fields when showing content. It would be great if there was a way to tell blazer that a column is encrypted, so that it decrypts before showing it in the result screen.

Thanks

**Comment by ankane** [comment]
Hey @bo-oz, thanks for the suggestion! There isn't currently a way to do this, but I'm open to suggestions about how you would design this.

**Comment by ankane** [comment]
Cleaning up stale issues. If anyone has ideas for how they would design this, feel free to respond below or open a new issue.
