### ISSUE TITLE
JS and HTML are being escaped and displayed on the page

### ISSUE THREAD

**Issue by devadmin-apto** [ankane/blazer#275]
What I am seeing is exactly what #263 was showing under exactly the same circumstances.  He said it magically fixed itself but mine still hasn't :)

Anybody else have this problem and any hints to fix will be appreciated!  

-Andy Galewsky

**Comment by ankane** [comment]
Hey Andy, unfortunately, I'm not sure how to reproduce. Are there any warnings in the JavaScript console, and are you seeing the issue with a fresh Rails app?

**Comment by devadmin-apto** [comment]
There is not a peep of errors in any of the logs or consoles.  
Turbolinks are being used in this app - have you seen that as a problem before?   

I will spin up another project as well and see if it happens there..

-Andy

**Comment by ankane** [comment]
Blazer itself doesn't use Turbolinks, but maybe if you load Blazer from a page that uses Turbolinks i it causes issues? Let me know what you find.

**Comment by ankane** [comment]
Cleaning up issues (not clear how to reproduce)
