### ISSUE TITLE
[idea] Enable schema selection by (smart) variables

### ISSUE THREAD

**Issue by maerch** [ankane/blazer#276]
👋Thanks for this awesome library!

We have a multi-tenant system where we use Postgres schemas to separate the tenants (pretty common with the Apartment gem). Blazer-wise it would be awesome to select a tenant for a given query with a smart variable. This would improve our queries/dashboard and analytics in general massively.

However, this does not work because variables are quoted and thus cannot be used as a schema. It seems there is some special logic needed to implement this.

I would like to work on a PR to add this feature if you think that this would be of any benefit and you would like to merge it at some point in the future.

**Comment by archonic** [comment]
@maerch I'd love to see this feature as well. It seems like it shouldn't be that difficult to implement. Have you started a fork for this feature?

**Comment by maerch** [comment]
Not yet. Wanted to wait and see first.

**Comment by ankane** [comment]
Hey @maerch, thanks for the suggestion. I'm hesitant to add a feature like this since it'll allow for SQL injection via query parameters. I was hoping there'd be a safe way to convert a schema/table name to identifier, like:

```sql
SELECT * FROM ({schema} || '.table')::regclass LIMIT 10
```

But I haven't been able to find one without writing a custom function.

**Comment by archonic** [comment]
An array of all tenant schema names is available with 'Apartment::Tenant'.
That could be used for a select in the interface and for whitelisting.

**Comment by maerch** [comment]
Metabase has similar concerns about [this](https://github.com/metabase/metabase/issues/4639) for a long time and haven't found a generic solution AFAIK.

However, I also think @archonic 's solution with a whitelist should be sufficient and safe for the most common use case. It just needs to be a "special" smart variable.

**Comment by ankane** [comment]
Unfortunately, I don't want to add any Apartment-specific features to Blazer. Overall, I think there's a low chance of adding support for this, but if either of you decide to fork for your own app, happy to take a look at the approach you come up with.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by archonic** [comment]
FYI I ended up moving ahoy tables to the public schema and extending the attributes to include `current_account.id`. So we do have a sensible way around this issue, as long as moving blazer tables into the public schema is acceptable.
