### ISSUE TITLE
[Idea] Run Blazer inside Docker

### ISSUE THREAD

**Issue by stvhanna** [ankane/blazer#277]
@ankane Thanks for building a great tool Blazer!

I'm trying to run it using Docker and I'm getting an error. Posted about it on StackOverflow:
https://stackoverflow.com/questions/60080126/how-to-fix-bundler-not-finding-rails-inside-docker-container

Any help would be greatly appreciated!

**Comment by ankane** [comment]
Hey @stvhanna, check out https://github.com/buren/ghost_blazer.

**Comment by ankane** [comment]
I threw together an experimental Docker image: https://github.com/ankane/blazer-docker

**Comment by stvhanna** [comment]
@ankane Excellent, thank you for moving swiftly to create the experimental repo! Will leave feedback on there. Much appreciated!
