### ISSUE TITLE
Table rendering issue

### ISSUE THREAD

**Issue by kb** [ankane/blazer#278]
Hi There,

I just went through the installation setup for blazer (version 2.2.1) within rails (6.0.2.1). Overall blazer is functional, however it seems that the views for search results are not rendering correctly (newlines, javascript, etc). Has anyone experienced this before? Any pointers on how to best troubleshoot? Perhaps the html is getting escaped somewhere?

![image](https://user-images.githubusercontent.com/6320/74938362-dd98f480-53bb-11ea-907f-4effb0d8159e.png)

**Comment by ankane** [comment]
Hey @kb, check out #263 and #275.

**Comment by kb** [comment]
Thanks for the pointer to those issues @ankane. I'll research things a bit more locally and see if I can come up with a repro case.

**Comment by kb** [comment]
I've traced the issue to an add-on gem for turbolinks I use called [turbolinks_render](https://github.com/jorgemanrubia/turbolinks_render). My work around was to fork blazer and add the initializer they describe in the readme to disable the gem's functionality. Likely not a change you'd want to incorporate into blazer itself, so I'll maintain my own fork for now. From what I've read turbolinks 6 is looking to incorporate a solution for what tubolinks_render provides, so hopefully in the future this is an easier configuration option that can be handled in the main app and not an engine like blazer.

**Comment by ankane** [comment]
Hey @kb, thanks for following up. Agree we don't want to make any changes to Blazer for this. Ideally, the `turbolinks_render` gem would let you exclude specific paths.

For future readers, the fix is an initializer with:

```rb
Rails.application.config.turbolinks_render.render_with_turbolinks_by_default = false
```
