### ISSUE TITLE
[Idea] Configure Blazer within an initializer

### ISSUE THREAD

**Issue by alexeisersun** [ankane/blazer#280]
Hi,

I was thinking about how developers configure Blazer. I've seen that Blazer uses `config/blazer.yml` under the hood to load all settings. I think of adding an initializer as just another option to configure the engine.

The idea is expose a `configure` method that looks like this:
```ruby
Blazer.configure do |config|
  config.data_sources = { hash of sources }
  config.async = true
  # and many more configs
end
```
... instead of this:
```yaml
data_sources: 
  source1: ...
  source2:
async: true
# and so on
```

I've seen this pattern in many Rails engines and just thought it is cool to have something like this in Blazer too, as one of configuration options.

**Comment by ankane** [comment]
Hey @alexeisersun, thanks for the suggestion. However, I don't think it makes sense to support another configuration method.
