### ISSUE TITLE
Error with `generate_series`

### ISSUE THREAD

**Issue by 6temes** [ankane/blazer#283]
Hi,

I am getting an error when trying to execute a statement containing "generate_series":

![image](https://user-images.githubusercontent.com/5655861/78618118-8344ec00-78b4-11ea-98c0-e53d01039bc6.png)

The error log is:

![image](https://user-images.githubusercontent.com/5655861/78618169-9952ac80-78b4-11ea-8264-0c18562440e8.png)

I have no issues when I execute the statement in the console.

Rails 6.0.2.2
Ruby 2.6.6 
PostgreSQL 10.11
Blazer 2.2.1

**Comment by ankane** [comment]
Hey @6temes, you likely had `GENERATE_SERIES` selected when you clicked run, which only executes that part of the query.

**Comment by 6temes** [comment]
I finally found out.

Cloudflare was blocking the queries with SQL in it. I fixed it by whitelisting my IP address.

**Comment by ankane** [comment]
Thanks for following up!
