### ISSUE TITLE
READONLY user on Postgres causes Internal Server Error

### ISSUE THREAD

**Issue by stevevance** [ankane/blazer#286]
I set up Blazer using my normal PostgreSQL user with all privileges. I set up queries and dashboards, and it all works nicely and looks great. Note that I'm using Docker because I couldn't actually get the Ruby on Rails instructions working (my experience is in PHP).

I then created a READONLY user on PostgreSQL per the instructions (changing the username and password to one of my choosing). 

When I start the app with that user's credentials, the following error is logged:

````
Completed 500 Internal Server Error in 492ms (ActiveRecord: 267.6ms | Allocations: 11420)
  
ActiveRecord::StatementInvalid (PG::InsufficientPrivilege: ERROR:  permission denied for table blazer_audits
):
````

I connected to the database with the readonly user just to be sure it could SELECT tables, and it can definitely do that, outside of Blazer. 

I'm looking at `blazer_audits` and it seems like Blazer needs a user with the INSERT privilege to add rows to that table.

**Comment by ankane** [comment]
Hey @stevevance, the user in `DATABASE_URL` needs write access to all the Blazer tables.

You'll want to put the read-only user in `blazer.yml` (see [Docker customization](https://github.com/ankane/blazer-docker#customization)).

I also just pushed an update to `ankane/blazer:latest` where you can set `BLAZER_DATABASE_URL` to be the read-only user without customizing `blazer.yml`. https://github.com/ankane/blazer-docker/commit/417520a53c54250310e8c7fecdec544043c5db51

**Comment by stevevance** [comment]
It worked. Thank you
