### ISSUE TITLE
NULL and NOT NULL smart variable option

### ISSUE THREAD

**Issue by pelted** [ankane/blazer#288]
Is there a way to provide `NULL` or `NOT NULL` options in a smart_variable? Trying to come up with what amounts to a toggle for null or not null values.

I've tried a few different options but they don't generate valid syntax.
```yaml
smart_variables":
    staff: {"NULL": "False", "NOT NULL": "True"}
```

```yaml
smart_variables":
    staff: ["NULL", "NOT NULL"]
```

but obviously these generate quoted strings

```sql
WHERE
    staff_id IS 'NOT NULL'
```

**Comment by ankane** [comment]
Hey @pelted, all variables are quoted to prevent SQL injection, so there's not a way to do this.
