### ISSUE TITLE
OCIError: ORA-00932: inconsistent datatypes: expected - got CLOB

### ISSUE THREAD

**Issue by pandu-49** [ankane/blazer#291]
Hi,

I have installed blazer and when I tried to access it. It thrown an error ORA-00932.
I'm using oracle as data source and I came to know that it is causing error when we are trying to order based on a text column.  The migration files were created blazer_dashboards table structure as below.

create_table "blazer_dashboards", force: :cascade do |t|
    t.integer "creator_id", precision: 38
    t.text "name"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["creator_id"], name: "index_blazer_dashboards_on_creator_id"
end

Below is the output from rails browser console.

> >> @dashboards = Blazer::Dashboard.order(:name)
> ActiveRecord::StatementInvalid: OCIError: ORA-00932: inconsistent datatypes: expected - got CLOB from stmt.c:267:in oci8lib_260.bundle
> >> @dashboards = Blazer::Dashboard.order(:creator_id)
> => #<ActiveRecord::Relation []>

Can someone please help me to resolve this. I'm hoping if we change name from text to string it may resolve the issue but it may break something else. 

Thanks!

EDIT1: I have changed name column in blazer_dashboards table to string and the page is loaded without error.

**Comment by ankane** [comment]
Hey @pandu-49, thanks for the sharing the fix. Using `string` instead of `text` should be totally fine.
