### ISSUE TITLE
Unknown adapter - oracle_enhanced Blazer::Error (Unknown adapter)

### ISSUE THREAD

**Issue by pandu-49** [ankane/blazer#293]
Hi,

I followed the documentation to integrate blazer along with Oracle as DB. I'm using https://github.com/rsim/oracle-enhanced as the adapter. Unfortunately blazer is throwing an error saying that it is an unknown adapter - **Blazer::Error (Unknown adapter)**. I have given configuration like below.

> data_sources:
>   main:
>     adapter: oracle_enhanced
>     username: db_username
>     password: db_password
>     statement_limit: 250
>     url:  <%= ENV['ORACLE_HOST']  %>

Can someone please help me to know if this is the correct syntax that blazer is expecting or did I missed anything here?

I have also checked blazer code to see if **orance_enhanced** adapter is added or not. Unfortunately I dit not find anything related to it.

Thanks!

**Comment by ankane** [comment]
You'll want to combine it into a single URL (the same format as a Rails database URL).

```yml
data_sources:
  main:
    url: oracle_enhanced://db_username:db_password@db_host:db_port/db_name
```

**Comment by pandu-49** [comment]
Hey @ankane, I've tried using as you said. Then it is raising an error like below. I also tried using dash instead of underscore.

URI::InvalidURIError (bad URI(is not URI?): oracle_enhanced://username:password@hostname:port_number/database_name)

**Comment by ankane** [comment]
It looks like it does need to be a dash instead an underscore. If there are any special characters in the password, be sure to URL encode them.

```ruby
require "cgi"
CGI.escape("p@assword") # p%40assword
```

It'll parse once everything is correct:

```ruby
URI.parse("oracle-enhanced://username:password@hostname:1234/database_name")
```

**Comment by pandu-49** [comment]
Hi @ankane, When I used hyphen it not raising bad URI error. However, It is not showing the schema when we accessed schema page. Moreover, when I tried to create a query the error says
**OCIError: ORA-00933: SQL command not properly ended**. 

The good thing is that it is creating Blazer:Audit records in the database. Could you help me here to resolve this. I would love if you help to make it happen.

Thanks

**Comment by ankane** [comment]
I updated the docs in the readme to make the configuration more clear. You'll need to run with it from here. The logs and stack trace should show you if there are issues with individual queries, and feel free to submit another PR if more fixes are needed.

**Comment by pandu-49** [comment]
@ankane Thanks for the help. I'm able to connect and run the queries. However, still I'm unable to see the schema. Something I need to check for more. Sorry for the trouble.

Thanks a lot 👍

**Comment by ankane** [comment]
Glad to hear it's working.

**Comment by pandu-49** [comment]
@ankane May I know what is the earliest version of oracle which will be supported by Blazer? We are currently using Oracle 12.
