### ISSUE TITLE
Users can be able to perform querying on other schemas even when schemas mentioned in blazer.yml

### ISSUE THREAD

**Issue by pandu-49** [ankane/blazer#294]
Hi,

I have specified my schemas list which only I wanted to perform querying and schema list. Still I can perform querying operations on tables out of given schemas list.

Example: 
I have given schemas value like below
schemas: 'MYSCHEMA'
If I run a query on a table which is not belong to given schema it is giving result.

**Comment by ankane** [comment]
Hey @pandu-49, the `schemas` option only changes which schemas are shown in the table preview dropdown. You'll need to set permissions on the database user to limit access to specific schemas.
