### ISSUE TITLE
[Idea] Forecasting for charts with multiple lines

### ISSUE THREAD

**Issue by groe** [ankane/blazer#299]
Hi,

I noticed the "Forecast" button only appears for queries / charts with 1 line. It would be awesome if it was possible to get forecasts for all lines in a chart, if there are multiple.

Thoughts?

I'm using Trend.

**Comment by groe** [comment]
Hi @ankane, thanks for the response! Are you referring to Prophet forecasting, or Trend, or both? I've been using Trend locally and it seems to be a lot faster than that

**Comment by ankane** [comment]
That's what I've seen with Trend. Not sure if it's helpful for your case, but we could increase the limit a bit (3 or 5 maybe) if you'd like to submit a PR.

**Comment by ankane** [comment]
Cleaning up issues
