### ISSUE TITLE
Cannot use dashboards with params anymore

### ISSUE THREAD

**Issue by Kani999** [ankane/blazer#301]
Hello, 

when I create a query with params, it works fine.

But when I create a dashboard with this query I throws an error about an unpermitted parameter. (The parameter name is 'year' but it happens with whatever name)

What could be a problem?

**Comment by ankane** [comment]
Hey @Kani999, I'm not sure I totally follow. Can you give detailed instructions on how to reproduce, and any relevant log output?

**Comment by Kani999** [comment]
Ok, for example.

1) I create a query with parameter `number`
```
SELECT * 
from (SELECT 1,2,3) as one 
where 1 = {number}
```
The query works fine.

2) I create a new dashboard with this query
- When I open the dashboard and enter the parameter, nothing is shown.
- I get an error
  - `found unpermitted parameter: :number`

I'm using Strong Parameters but this never happened before. I also can try to downgrade the version of blazer.

I'm currently using `blazer` 
```
    blazer (2.2.5)
      activerecord (>= 5)
      chartkick (>= 3.2)
      railties (>= 5)
      safely_block (>= 0.1.1)
```


### log after entering parameter

```
 !!! UNPERMITTED: !!! found unpermitted parameter: :number
Redirected to /admin/blazer/dashboards/21-test-xxx
Started GET "/admin/blazer/dashboards/21-test-xxx" for IP at 2020-08-27 09:22:03 +0200
Processing by Blazer::DashboardsController#show as HTML
Parameters: {"id"=>"21-test-xxx"}
  Blazer::Dashboard Load (0.8ms)  SELECT `blazer_dashboards`.* FROM `blazer_dashboards` WHERE `blazer_dashboards`.`id` = 21 LIMIT 1
 Blazer::DashboardQuery Load (0.8ms)  SELECT `blazer_dashboard_queries`.* FROM `blazer_dashboard_queries` WHERE `blazer_dashboard_queries`.`dashboard_id` = 21 ORDER BY `blazer_dashboard_queries`.`position` ASC
```

**Comment by ankane** [comment]
Thanks @Kani999, I'm able to reproduce. Will try to get a fix up shortly.

**Comment by ankane** [comment]
Give master a shot.

**Comment by Kani999** [comment]
> Give master a shot.

Even with the `2.2.6` version, the problem is still the same.

**Comment by ankane** [comment]
To load the gem from GitHub, use:

```ruby
gem 'blazer', github: 'ankane/blazer'
```

**Comment by Kani999** [comment]
> To load the gem from GitHub, use:
> 
> ```ruby
> gem 'blazer', github: 'ankane/blazer'
> ```

Sorry I did not realize that.

Yes with `gem 'blazer', github: 'ankane/blazer'` everything works fine.

**Comment by Kani999** [comment]
I'm trying now to create 3 queries 
 - 1) With a parameter
 - 2) With a different parameter name
 - 3) Without a parameter

Then When I create a dashboard which contains these three queries it still does not work

**Comment by ankane** [comment]
Alright, should be good now.

**Comment by Kani999** [comment]
@ankane - I can confirm, that all of my dashboards work properly. 

Thank you for quick solution.

**Comment by ankane** [comment]
Great, thanks (meant to update here when it was released, 20 days ago...)
