### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by kwent** [ankane/blazer#303]
Hi,

Would be nice to have a healtcheck endpoint especially useful in a container environment to make sure application is loaded and healthy. ( We could use `/` but when behind auth, it does not work ) and `/health` or `/healthz` is a better convention.

Regards

**Comment by ankane** [comment]
Good idea, added to the Docker image: https://github.com/ankane/blazer-docker/commit/2e6f012a52eba5bbf5c18166218d9456c986375b
