### ISSUE TITLE
Prevent queries from loading on page load

### ISSUE THREAD

**Issue by voltechs** [ankane/blazer#305]
Is there a setting that disables auto loading charts/queries on page load?

We have a number of pretty beefy result sets that hose the browser, so our users are instructed to click download, however that still leaves a query running.

Can we signal to Blazer that particular queries are expected to return large datasets, and instead of autoloading, it presents a execute and download button?

**Comment by ankane** [comment]
Hey @voltechs, there's not any feature like that. I'd like to move the result rendering client-side if possible, which should prevent the browser from freezing with large datasets.

**Comment by ankane** [comment]
Cleaning up issues
