### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by jatinbhappy** [ankane/blazer#306]
Hi Team, 

While running some bigger query, I am getting an error, GatewayTime out, Do you guys have any settings to increase the timeout, or suggest me how to resolve

**Comment by ankane** [comment]
Hey @jatinbhappy, a gateway timeout is likely caused by the load balancer, so one option is to adjust those settings. If the problem is queries taking too long to run (vs loading too much data), you can try the `async: true` option (see readme for details).
