### ISSUE TITLE
UUID Support

### ISSUE THREAD

**Issue by mdjamal** [ankane/blazer#307]
Hi,

If Rails is configured to use :uuid as the primary key for all tables, eg if config/initializers/generators.rb contains:

`Rails.application.config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end`

Creates all blazer tables primary and foreign key columns with data_type uuid, but the Blazer::Query fails. For example:

Couldn't find Blazer::Query with 'id'=90acf5b4
when the actual query_id is `{"id"=>"90acf5b4-ceca-4904-8599-58b87bfdef50-users-total-count"}`

Additionally not able to create queries when `audit:` is set to `true`

(PG::NotNullViolation: ERROR:  null value in column "query_id" violates not-null constraint...

Just checking to see if blazer works with UUID.

Thanks.

**Comment by ankane** [comment]
Hey @mdjamal, as you probably guessed, Blazer doesn't support UUID primary keys for its tables. You'll want to manually update the install migration to use numeric ids.

**Comment by mdjamal** [comment]
@ankane yes and thanks for confirming.
