### ISSUE TITLE
Cannot create a query without a name

### ISSUE THREAD

**Issue by coorasse** [ankane/blazer#312]
After installing the tool, I directly went to the query creator to test it and boom!
By including a simple query and hitting "Create", I get a 500 Internal Server error on next page.
![image](https://user-images.githubusercontent.com/1319150/99514388-fd316d80-298b-11eb-9f1a-f2415add9dfd.png)

After debugging I identified the problem here since I didn't give a name to my query: https://github.com/ankane/blazer/blob/master/app/controllers/blazer/queries_controller.rb#L244

it results in the following error: `NoMethodError - undefined method `parameterize' for nil:NilClass:`

all that while processing `Processing by Blazer::QueriesController#run as HTML`.

How would you like it to be solved? I can happily open a PR for that. I am brand new to the project but we have two options:
* make the name mandatory
* `@filename = @query.name.parameterize if @query&.name`

let me know! 😄

**Comment by ankane** [comment]
Hey @coorasse, it sounds like you may have a gem installed that's turning empty strings into `nil` for model attributes. It looks like `@filename` isn't used anymore and can be removed, but other behavior in the app may also be broken (and it's not supported).

**Comment by coorasse** [comment]
Could it be because I am using an oracle adapter? what about simply doing `@filename = @query.name.to_s.parameterize` then?

**Comment by ankane** [comment]
Hey @coorasse, I removed the variable (since it's not being used anymore), but as I mentioned earlier, there may be other behavior that doesn't work as expected if your app is configured to strip model attributes.

**Comment by coorasse** [comment]
Thanks. Yes, this might be due to due Oracle adapter
