### ISSUE TITLE
Cant find any saved query with oracle

### ISSUE THREAD

**Issue by giovapanasiti** [ankane/blazer#314]
I'm using Oracle 11g and having issue with retrieving saved queries. 

```
Blazer::Query Load (1.5ms)  SELECT id, name FROM "BLAZER_QUERIES" WHERE "BLAZER_QUERIES"."STATUS" = :a1 AND (blazer_queries.name <> '') ORDER BY "BLAZER_QUERIES"."NAME" ASC  [["status", "active"]]
```

This statement return no records, but if I remove (blazer_queries.name <> '') I see all my queries correctly both from console and from quering my db directly.

Has anyone found a similar issue?  To build a dashboard I'm actually populating BLAZER_DASHBOARD_QUERIES table manually

**Comment by ankane** [comment]
Hey @giovapanasiti, think it's probably the same cause as #312 (empty strings being changed to `nil`). If it's the adapter, I'd try filing an issue to have it behave the same as the other Active Record adapters. Also, fwiw, Oracle is supported as a data source, but not for Blazer tables, so you may run into other issues as well.

**Comment by giovapanasiti** [comment]
thank you so much for the feedback. Although when I navigate in the blazer tables with my database tool I see the name of the queries. I'll try to fix it and I'll let you know anyway!

**Comment by ankane** [comment]
I switched the query to use `where.not` instead of a string on master, so you may want to see if that fixes it.

**Comment by coorasse** [comment]
I am also using Blazer with Oracle. I can confirm you that the master version works for me. 
That's exactly the patch I also applied in our version before. 👍 
Thanks

**Comment by ankane** [comment]
Thanks @coorasse, glad to hear that fixed it
