### ISSUE TITLE
Problem with clear_helpers added in 2.4 and embedding Blazer within another app

### ISSUE THREAD

**Issue by denny** [ankane/blazer#315]
Hi,

I'm loading Blazer inside the admin area of my application, so Blazer's templates define the main content area of the relevant pages, but my admin area's layout, menus, etc are rendering around the edges.

The change on line 9 here wipes out all of my app's helpers, which are used in those surrounding templates - meaning that none of my admin pages wrapping Blazer will load with Blazer 2.4:
https://github.com/ankane/blazer/blob/6048a2fdead7f361f1bd156334e7b7d2893d5346/app/controllers/blazer/base_controller.rb#L9

I wonder if it clearing the helpers could be made a configurable option? I have no opinion on the best default - I'm guessing my usage pattern is a minority one, and it sounds like this addition has fixed problems for other people - but it'd be great to have the option to keep my helpers if possible.

Thanks,
Denny

**Comment by ankane** [comment]
Future readers, see #316
