### ISSUE TITLE
[Idea] Support for Athena workgroup

### ISSUE THREAD

**Issue by MasterOdin** [ankane/blazer#320]
It would be nifty to be able to set the workgroup to use on running queries against Athena. Looking at the [`start_query_execution`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Athena/Client.html#start_query_execution-instance_method) documentation, it looks like support for this could be done by adding the `work_group` parameter to. Looking at the [workgroups docs](https://docs.aws.amazon.com/athena/latest/ug/workgroups.html) as well as other athena clients, I believe you can assume a default setting of `primary` if it is not set by the user. Looking at the code (mind you I do not do Ruby almost ever), I believe one could modify:

https://github.com/ankane/blazer/blob/79789af2327f7427b5653d7cd4798a8282c77ddb/lib/blazer/adapters/athena_adapter.rb#L13-L23

to be something like:

```ruby
            client.start_query_execution(
              query_string: statement,
              # use token so we fetch cached results after query is run
              client_request_token: Digest::MD5.hexdigest([statement,data_source.id].join("/")),
              query_execution_context: {
                database: database,
              },
              result_configuration: {
                output_location: settings["output_location"]
              },
              work_group: settings["workgroup"] || "primary",
            )
```

and I think this would achieve it?

**Comment by ankane** [comment]
Hey @MasterOdin, thanks for the suggestion. I'll take a look at adding it next time I'm working on Athena (not sure exactly when that'll be).

**Comment by ankane** [comment]
Added in the commit above. Thanks for the suggestion @MasterOdin!
