### ISSUE TITLE
Are NULL values ignored?

### ISSUE THREAD

**Issue by vitobotta** [ankane/blazer#322]
Hi, 

this gem looks awesome, thanks. I am trying to create line charts to see how many users signed up per week and how many confirmed their account. But rows with confirmed_at NULL seem to be ignored, i.e. if I run the query `SELECT confirmed_at FROM users ` it only outputs non null value, but there are some null values. I saw another issue about null values but I am not sure these are related.

How can I ensure that null values are not ignored?

Thanks!

**Comment by ankane** [comment]
Hey @vitobotta, NULL values should show up in the table, but won't show up in a line chart since they won't have a value for the x-axis. If you're trying to chart the number of users who confirmed each week, you'll want a query like:

```sql
-- for Postgres
SELECT date_trunc('week', confirmed_at), COUNT(*) FROM users WHERE confirmed_at IS NOT NULL GROUP BY 1
```

 which won't have NULL values.

**Comment by vitobotta** [comment]
Thanks Andrew for the clarification and again for the awesome gem :)
