### ISSUE TITLE
[Idea] Support for Query Variables in Checks or Query Variables defaults

### ISSUE THREAD

**Issue by bkonetzny** [ankane/blazer#327]
Currently it seems there is no UI in the Check creation process to add values for Query Variables. It would be cool to either add an UI for this to the Check creation, or set some defaults for the variables in the query, so these get picked up when they are used in a Check.

**Ideas:**
* Add an UI to configure Query Variables for the Check.
* Add defaults to Query Variables (e.g. `{variable|default}` -> `{country|"Germany"}`)

What do you think?

**Comment by ankane** [comment]
Hey @bkonetzny, thanks for the suggestion! I've considering something similar for dashboards in the past, but don't think it's worth the extra complexity.
