### ISSUE TITLE
Can't query a JSON properties in a MySQL DB

### ISSUE THREAD

**Issue by lorismaz** [ankane/blazer#328]
Hi,

I'm trying to create a pie chart from ahoy analytics
This is my query (I use a MySQL db)

```
SELECT JSON_EXTRACT(properties, '$.store') AS store, COUNT(*) AS pie 
FROM ahoy_events 
GROUP BY 1;
```

and I get an "An error occurred" message, while it works well when trying to do the same pie with a `ahoy_events.name`.

Is this a limitation ?

**Comment by ankane** [comment]
Hey @lorismaz, sounds like a possible bug, but I'm not sure how to reproduce. Can you share the stack trace from the server?

**Comment by kaycbas** [comment]
Hi, I'm also having this same issue. I'm trying to use blazer to visualize ahoy analytics, but I'm unable to query the JSON properties. I'm using a PostgreSQL db. Here's my query:
```
SELECT JSON_EXTRACT(properties, '$.response') AS response
FROM ahoy_events 
```
The error in the Blazer UI is: 
```
function json_extract(jsonb, unknown) does not exist LINE 1: SELECT JSON_EXTRACT(properties, '$.response') AS response ^ HINT: No function matches the given name and argument types. Y
```
And on the server I see:
```
I, [2022-03-17T21:39:58.696425 #25903]  INFO -- : Started POST "/blazer/queries/run" for ::1 at 2022-03-17 21:39:58 -0700
I, [2022-03-17T21:39:58.698214 #25903]  INFO -- : Processing by Blazer::QueriesController#run as HTML
I, [2022-03-17T21:39:58.698300 #25903]  INFO -- :   Parameters: {"statement"=>"SELECT JSON_EXTRACT(properties, '$.response') AS response\r\nFROM ahoy_events \r\n", "data_source"=>"main", "run_id"=>"5c6c3155-d762-4db0-b7fc-68632b114448"}
I, [2022-03-17T21:39:58.703294 #25903]  INFO -- :   Rendering /Users/kevinbastoul/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blazer-2.5.0/app/views/blazer/queries/run.html.erb
I, [2022-03-17T21:39:58.703425 #25903]  INFO -- :   Rendered /Users/kevinbastoul/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blazer-2.5.0/app/views/blazer/queries/run.html.erb (Duration: 0.0ms | Allocations: 7)
I, [2022-03-17T21:39:58.703556 #25903]  INFO -- : Completed 200 OK in 5ms (Views: 0.4ms | ActiveRecord: 2.5ms | Allocations: 3989)
```
Is it possible to extract properties from a JSON column in Blazer? Thanks

**Comment by ankane** [comment]
Hey @kaycbas, you'll need to use Postgres functions / operators for Postgres: https://www.postgresql.org/docs/current/functions-json.html

**Comment by cianmce** [comment]
MySQL version 5.7+ supports JSON operations
E.g running this on MySQL v8 runs `2`
```sql
SELECT JSON_EXTRACT('{"a": 1, "b": 2, "c": 3}', '$.b') AS 'Result';
```

> https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
