### ISSUE TITLE
SQL Formatter/Beautifier

### ISSUE THREAD

**Issue by kmarsh** [ankane/blazer#331]
:wave: Thanks so much for blazer, it's a great utility for our small team.

One thing I miss from TablePlus (and Prettier) is a SQL formatter to tidy up queries. I've gotten so used to just mashing together some keys and hitting a button to make it look coherent. This might also be a good thing for less-experienced SQL writers to learn from as well.

I did some research and found https://github.com/zeroturnaround/sql-formatter which runs client-side and seems like it might be a relatively easy feature to implement. (In fact, I might be able to hack together a small bookmarklet. 🤔)

**Comment by ankane** [comment]
Hey @kmarsh, thanks for the suggestion! The project looks interesting, but it's not really a feature I'd like to include/support.
