### ISSUE TITLE
Conflicting error with another chart gem (apexcharts)

### ISSUE THREAD

**Issue by jvillarejo** [ankane/blazer#332]
Hi,

I'm having this error when trying to run a query and generating a chart:

`ActionView::Template::Error (unrecognized key: :library in ApexCharts::Options::RootOptions.):`

In my `Gemfile` I have the gem `apexcharts` which I use on my application. 
But I think the helper methods for building the charts are conflicting with the Chartkick helper methods.

Do you have any idea on how to solve it ?
If I can solve it on my application I would gladly submit a PR too if that's something that belongs here.

Thanks!

**Comment by ankane** [comment]
Hey @jvillarejo, thanks for reporting! You can try [prefixing the Apex charts](https://github.com/styd/apexcharts.rb#use-alongside-other-charting-libraries). It probably makes sense for Chartkick to have prefixed versions of its helpers so Blazer can use those.

**Comment by jvillarejo** [comment]
Thanks for your reply @ankane ! 
Wow I can't believe that was on the Apex charts Readme and I totally skipped it. 
I'm sorry, I'm so embarrassed. I'll try it. 

Thank you very much!
