### ISSUE TITLE
[Idea] show images on query results

### ISSUE THREAD

**Issue by lrgalego** [ankane/blazer#335]
We use blazer extensively for dashboards. 
There are times we want to see images related to entries in the databases, right now we can only see URLs.
It would be great if we could add some naming convention in the column to turn the value into an image instead.
I can work on it, just need some guidance on where to start.

**Comment by ankane** [comment]
Hey @lrgalego, good to hear from you! Looks like it's not currently documented, but there's an `images` option for this:

```yml
images: true
```

[Demo](https://blazer.dokkuapp.com/queries/14-images)

**Comment by lrgalego** [comment]
Great. works like a charm!
