### ISSUE TITLE
[Idea] render geojson areas in the map

### ISSUE THREAD

**Issue by lrgalego** [ankane/blazer#337]
At AdQuick we use the feature that renders pins in a map quite a lot.

Sometimes we need to check if a pin is inside an area on the map.
Right now I need to go out of blazer and make manual maps to render the areas using geojson.
If blazer could also render the geojson in the map, making those analyses would be as easy as writing a SQL query.

We can use [mapbox-gl-js](https://docs.mapbox.com/mapbox-gl-js/api/) to implement this with a good performance.

I can work on this but would appreciate some guidance on where to start.

**Comment by ankane** [comment]
Hey @lrgalego, would be curious to see what this looks like. The relevant code should be in a similar location as #336.
