### ISSUE TITLE
[Idea] Recursive queries

### ISSUE THREAD

**Issue by pedrocarmona** [ankane/blazer#339]
Hi @ankane,

Ideia for reusing queries.
 
```
Select * FROM users WHERE id IN ({blazer-query-1-admin_id})
```

A variable that would run blazer::query.find(1), and serialize `admin_id` from that query result set.

**Comment by ankane** [comment]
Hey @pedrocarmona, thanks for the suggestion, and sorry for the delay. It's a neat idea for reusing queries, but don't want to add the additional complexity.
