### ISSUE TITLE
Incorrect quoting of some smart variables 

### ISSUE THREAD

**Issue by brandondrew** [ankane/blazer#340]
I have this in my config file:

```
    smart_variables:
      period: ['days', 'weeks', 'months']
```

and this query to get all records from the last 24 hours in a particular table:

```
SELECT id,calnet_uid,code,label,status,current_at,created_at,updated_at
FROM public.badges AS "Badges"
WHERE "Badges"."current_at" BETWEEN NOW() - INTERVAL '{count} {period}' AND NOW()
ORDER BY "Badges"."current_at" DESC
```

The `{count}` variable is correctly inserted into the query, but the `{period}` variable has single quotation marks added with it, which breaks the query:

```
SELECT id,calnet_uid,code,label,status,current_at,created_at,updated_at
FROM public.badges AS "Badges"
WHERE "Badges"."current_at" BETWEEN NOW() - INTERVAL '2 'days'' AND NOW()
ORDER BY "Badges"."current_at" DESC
```

```
syntax error at or near "days" LINE 3: ...Badges"."current_at" BETWEEN NOW() - INTERVAL '2 'days'' AND... ^
```

**Comment by ankane** [comment]
Hey @brandondrew, variables are always quoted, so you'll need to account for this when writing queries. Instead of `INTERVAL '{count} {period}'`, you can use `({count} || ' ' || {period})::interval`.
