### ISSUE TITLE
[Idea] SELECT COUNT(*) query result shown while waiting for query to load data.

### ISSUE THREAD

**Issue by brandondrew** [ankane/blazer#341]
It would be extremely useful to see a a count of your query results—which is really fast—while waiting for your query results to load.  (In fact, it could be done automatically before you even run or preview the query, possibly.)

This early feedback would allow you to recognize what sort of volume of data you've just asked for, and give you an idea of how long you'll wait, and show you that the problem is not with Blazer, and allow you to make a better decision about whether to exit or make other plans (like getting coffee, switching to another app, etc.).

**Comment by ankane** [comment]
Hey @brandondrew, thanks for the suggestion. Running an extra query will create additional load on the database, so I don't think it makes sense for most situations.
