### ISSUE TITLE
[Idea] Cancel button for long queries

### ISSUE THREAD

**Issue by brandondrew** [ankane/blazer#342]
I have found the Blazer UI to be generally unresponsive while waiting for long queries to load.  (If I click the "Home" button, nothing happens.)  I haven't jumped into the code to figure out why, but it would be _very_ nice to have a way of canceling such queries.  That would require _at least the "Cancel" button_ to be responsive.

**Comment by brandondrew** [comment]
Interestingly, I haven't seen the same unresponsiveness since posting this.  Perhaps formerly I experienced it only when the browser was waiting to begin receiving _any_ data back from the server for truly ENORMOUS result sets?   Perhaps it only happens when the page is first loaded by not subsequently (or the reverse of that)?  I'm not sure.

Nonetheless, a cancel button would be nice, and could go well with #341

**Comment by ankane** [comment]
Hey @brandondrew, Blazer isn't really designed for very large result sets, so your browser may freeze when trying to load a lot of data. There's already a cancel button, but it'll only work before the query completes.
