### ISSUE TITLE
Not able to use cache feature

### ISSUE THREAD

**Issue by babarajay** [ankane/blazer#343]
Hello there,

I'm trying to use caching for my queries but everytime it executed rather getting results from the cache.

I also set the configs on the blazer.yml file for the cache. Here is the code spinet:

```
cache:
  mode: all
  expires_in: 60 # min
```

I've overridden the queries_controller and tried to add rails logger just to check the query and it's result and it never execute the below code:

```
elsif @run_id
         @timestamp = blazer_params[:timestamp].to_i
         @result = @data_source.run_results(@run_id)
         @success = !@result.nil?
          if @success
            @data_source.delete_results(@run_id)
            @columns = @result.columns
            @rows = @result.rows
            @error = @result.error
            @just_cached = !@result.error && @result.cached_at.present?
            @cached_at = nil
            params[:data_source] = nil
            render_run
```

I'm not sure what I'm missing here; Can anyone help me with this issue please?

Thank you!

**Comment by ankane** [comment]
Hey @babarajay, I'd check that caching is enabled in your application.

**Comment by babarajay** [comment]
@ankane thank for your reply.

Yes, caching is already enabled in my application but still facing this issue.

**Comment by ankane** [comment]
What's the output of cache logging?

**Comment by babarajay** [comment]
@ankane , actually, I'm trying to override the queries_controller and and passing arguments (params) in such a way that execute the below code snippet. That will bring the results from the cache.

```
elsif @run_id
         @timestamp = blazer_params[:timestamp].to_i
         @result = @data_source.run_results(@run_id)
         @success = !@result.nil?
          if @success
            @data_source.delete_results(@run_id)
            @columns = @result.columns
            @rows = @result.rows
            @error = @result.error
            @just_cached = !@result.error && @result.cached_at.present?
            @cached_at = nil
            params[:data_source] = nil
            render_run
```

The above code never executed though I'm passing params in the required fashion.

**Comment by ankane** [comment]
Unfortunately, I don't really follow what you're trying to do, but check out the Contributing Guide for where to get help.
