### ISSUE TITLE
Idea - add title just before graph

### ISSUE THREAD

**Issue by nicolas-besnard** [ankane/blazer#354]
Hi,

When I'm sending screenshots to my team, it could be useful to include the graph title and the value of the dynamic range.

I'm happy to work on this if it's a feature you'd like to include.

**Comment by ankane** [comment]
Hey @nicolas-besnard, thanks for the suggestion and volunteering to work on it, but I'd like to keep the charts simple/clean. You should be able to fork and add `title` to [this line](https://github.com/ankane/blazer/blob/ac7e02e0fe19ee6c0bc8c7f3ba87be0d260f8255/app/views/blazer/queries/run.html.erb#L49) in your own version.
