### ISSUE TITLE
[Idea] Support for Rails API projects

### ISSUE THREAD

**Issue by bradherman** [ankane/blazer#355]
When trying to install Blazer into a Rails API project the installation fails due to the missing asset pipeline.  Since the front-end functions as a mounted engine, it should be possible to generate the necessary backend for the web UI without relying on the asset pipeline from the including project (ie: Sidekiq web for instance)

**Comment by coder2000** [comment]
This also applies to users who may disable sprockets in favor of using webpacker 100%

**Comment by ankane** [comment]
Hey @bradherman, thanks for the suggestion, but it's not something I'd like to support. However, anyone is welcome to fork and maintain a version for the community.
