### ISSUE TITLE
Escape Characters for Queries

### ISSUE THREAD

**Issue by wdenny3885** [ankane/blazer#358]
I have searched the documentation, as well as posted to stack exchange. 

I can't seem to get blazer to work when searching strings in a query and using " or '. I have tried all the PG escape methods to no avail. 

Stack Exchange: [https://stackoverflow.com/questions/68925787/blazer-escape-characters/68926197?noredirect=1#comment121813464_68926197](url)

```
SELECT * FROM "search_filters"
where "params" like '%with_vehicles_id"=>[%'
LIMIT 100
```

Error:

```
syntax error at or near "LIMIT" LINE 3: LIMIT 100 LIMIT 1000 /*blazer,user_id:189,user_name:...^
```

**Comment by ankane** [comment]
Hey @wdenny3885, it looks like you may be running a modified version of Blazer that adds an extra limit.
