### ISSUE TITLE
Front page hard-codes limit to 200 items

### ISSUE THREAD

**Issue by tripleee** [ankane/blazer#361]
We are running Blazer as part of metasmoke, a back end system for keeping track of spam on the Stack Exchange network. (More info: https://charcoal-se.org/)

The Blazer instance is privileged to a subset of registered users, so I won't link to it, but we noticed that it no longer displays all the queries when you click "Home" and discovered that the limit is set to 200. There is no indication that anything has been left off, so it took a while to figure out why I could not find a query which I thought should be there.

See also our internal bug report at https://github.com/Charcoal-SE/metasmoke/issues/874

Repro steps require you to create enough queries to bring you past this limit, but if you can do that, should be easy to discover and assess.

**Comment by tripleee** [comment]
https://github.com/Charcoal-SE/metasmoke/issues/874#issuecomment-911373260 says:

> Same bug appears to be present in current upstream (based on code; haven't tested): https://github.com/ankane/blazer/blob/a505849e893abef50c4128c2b3bfc9fae5ad2c86/app/views/blazer/queries/home.html.erb#L125

**Comment by ankane** [comment]
Hey @tripleee, this is by design (for DOM performance). You can use the search box to narrow down the list of queries.

**Comment by tripleee** [comment]
But it only searches among those which are displayed on the page, at least in our installation; you really can't get beyond the 200th.

**Comment by ankane** [comment]
I'm not sure this is needed (or what it would look like), but feel free to share if you fork and implement.
