### ISSUE TITLE
No error with DB connection error

### ISSUE THREAD

**Issue by dogmatic69** [ankane/blazer#370]
I had the wrong host name and nothing happened, UI did not load at all but could see requests hitting the backend. 

Docs don't show how to enable debug, but after looking through the code I was able to get debug and see there was an issue connecting to the BD.

Would have been helpful if the UI showed some kind of connection error, or even the logs at the very least.

**Comment by ankane** [comment]
Hey @dogmatic69, I'm not really sure how to reproduce. Connection errors should show up in the logs as well as your error reporting service (and does when I test it).

**Comment by dogmatic69** [comment]
So I had an invalid hostname for reference, perhaps the timeout was longer than my patience waiting for an error?
