### ISSUE TITLE
Compatibility with Propshaft

### ISSUE THREAD

**Issue by jankeesvw** [ankane/blazer#379]
In Rails 7, the default is to compile assets is via [jsbuilding-rails](https://github.com/rails/jsbundling-rails) and [cssbuilding-rails](https://github.com/rails/cssbundling-rails) unfortunately Blazer relies on Sprockets because of the `//= require` in the sass files.

It would be great if Blazer worked with Propshaft.

**Comment by jankeesvw** [comment]
As a temporary workaround I added the compiled versions of the assets to our project, this is served by Propshaft:

![image](https://user-images.githubusercontent.com/167882/151872049-e42b0a46-98ca-4a64-bd07-33dbc77a9140.png)

**Comment by ankane** [comment]
Hey @jankeesvw, Sprockets is still the Rails default (`rails new hello && grep sprockets hello/Gemfile`) and what I think is the best choice for engines at the moment. It sounds like Propshaft may replace Sprockets at some point, so will revisit then. https://github.com/rails/propshaft#will-propshaft-replace-sprockets-as-the-rails-default

**Comment by jankeesvw** [comment]
While I 100% agree with your stance, I think more people are going to require this.

If someone willing to join I would love to create a PR for this.

In the meantime I'll close this issue 👍

**Comment by ankane** [comment]
Added experimental support in the commit above if you want to give it a shot.
