### ISSUE TITLE
NameError: uninitialized constant Blazer::YAML while deploying in production

### ISSUE THREAD

**Issue by VinoyN** [ankane/blazer#38]
I get this error while deploying on production (unicorn) works fine in development (webrix).
Tried setting the BLAZER_DATABASE_URL environment through profile file as well as environment.rb

NameError: uninitialized constant Blazer::YAML
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/blazer-1.0.4/lib/blazer.rb:30:in `settings'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/blazer-1.0.4/lib/blazer/engine.rb:9:in `block in <class:Engine>'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
/var/www/dashboard/releases/20151215121328/config/environment.rb:5:in `<top (required)>'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:328:in `require'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:328:in `require_environment!'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/www/dashboard/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)

**Comment by ankane** [comment]
I've added code to require yaml explicitly.  See if master works for you.

Looks like it may be an issue with Rails 4.2.1 and 4.2.2. https://github.com/rails/rails/issues/20875

**Comment by VinoyN** [comment]
Thank you. require yaml did the trick.
P.S using searchkick and ahoy in production now. Great work.

**Comment by ankane** [comment]
Awesome, glad that fixed it.
