### ISSUE TITLE
Number of items shown in charts

### ISSUE THREAD

**Issue by quovai** [ankane/blazer#380]
Hello,

when creating a query that returns more than 20 items, the resulting chart seems to be anyway limited to 20:

![image](https://user-images.githubusercontent.com/19818047/152061597-929ad4f5-cf84-43b9-9629-9174f64c8320.png)

Is it a hardcoded limit or is there a configuration option to overcome this?

Thanks
Stefano

**Comment by ankane** [comment]
Hey @quovai, the charts become unreadable with too many items, so 20 seemed like a good limit. There's not an option, but you can fork and edit it in these two places. https://github.com/ankane/blazer/blob/34c60e3af5c6ca6cabae3a8a5cbfb7bd2211fe71/app/views/blazer/queries/run.html.erb#L116-L118

**Comment by quovai** [comment]
Thank you. I'll try to fork and modify.

While what you say is correct (charts tend to be cluttered if too many items) it is also probably more true for bar charts than for line charts.

It is a bit confusing when you have more than 20 elements in the table but only 20 elements in the chart.

Would it be possible to introduce this as a config option?

Stefano

**Comment by ankane** [comment]
The limit only applies to column charts, fwiw.

I don't think it's worth adding an option.
