### ISSUE TITLE
[Idea] Grouping queries in folders 

### ISSUE THREAD

**Issue by quovai** [ankane/blazer#381]
When creating many queries it's difficult to recognise them at first glance.
It would be great to have the possibility to group queries in folders. Now the only way to group
queries together seems to be using a PREFIX__

![image](https://user-images.githubusercontent.com/19818047/152062301-19f3cd37-c453-4a45-bc9d-da01626e0aee.png)

**Comment by ankane** [comment]
Hey @quovai, I've considered adding folders (and experimented with tags), but prefer to keep things simple for now. If you use brackets for the prefix (`[some prefix]`), it'll keep them grouped together on the home page and hide the prefix on dashboards.

**Comment by quovai** [comment]
Thank you. Do you have any pointers in case I would like to try to form and implement (keeping the philosophy of "simplicity" that I appreciate a lot)?

**Comment by ankane** [comment]
I'd implement whatever makes the most sense to you (it's not something I'd like to change in the official version).
