### ISSUE TITLE
Undefined "prepared_statements?" method for Rails < 7.0

### ISSUE THREAD

**Issue by giemsky** [ankane/blazer#394]
At the beginning I would like to thank you for this gem and all your work.

Looks like changes introduced in Blazer 2.6 has broken apps using MySQL and Rails < 7.0. 

The following exception is raised:
```
NoMethodError - undefined method `prepared_statements?' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x000000010e905b78>
```

From what I researched `prepared_statements?` was added as an alias to `prepared_statements` in Rails 7 https://github.com/rails/rails/commit/da26910fbcfa3aa23ebc1474b43b048b78b60e4c

**Comment by ankane** [comment]
Fixed by #393
