### ISSUE TITLE
[Idea] Allow state change check email row/column limits to be configurable

### ISSUE THREAD

**Issue by frank-west-iii** [ankane/blazer#396]
We use checks to send out information to users that don't have access to blazer itself. I have overridden the email template to our liking removing the hard coded limits, but there is still a hard coded limit in the model code. I could monkey patch that, but I would rather not.

https://github.com/ankane/blazer/blob/a505849e893abef50c4128c2b3bfc9fae5ad2c86/app/models/blazer/check.rb#L71

Would you be up to accepting a PR that makes these limits configurable, but defaulting to their current behavior?

**Comment by ankane** [comment]
Hey @frank-west-iii, sorry for the delay. It's not something I'd like to make configurable.
