### ISSUE TITLE
Blazer drops formating when query saved

### ISSUE THREAD

**Issue by klarazetkin** [ankane/blazer#399]
The problem is as follows. You write a query with formating.

![image](https://user-images.githubusercontent.com/38485331/169784382-996bd0a9-28ff-48a2-aebf-c15284dd2d7b.png)

Then you save or update the query. When you look at the saved query code it keeps formating. 

![image](https://user-images.githubusercontent.com/38485331/169784494-30f9ff94-4337-4cdf-bdb7-6c7c61a8a48b.png)

But as soon as you start editing the query, the formating is dropped. 

![image](https://user-images.githubusercontent.com/38485331/169784650-5f3cbf19-d42a-4ef5-860e-f861ef44a574.png)

If a query is a complicated one, it's a pain. Very annoying. :(

**Comment by ankane** [comment]
Hey @klarazetkin, unfortunately, I'm not sure how to reproduce. What OS and browser are you using (including versions)?

**Comment by klarazetkin** [comment]
Hi, @ankane! I'm using Ubuntu 20.04 and Version 101.0.4951.64 (Official Build) snap (64-bit). I tried blazer with Firefox Browser 100.0.2 (64-bit) and the bug reproduced. Should I try some other browser, just Chrome maybe?

**Comment by ankane** [comment]
Trying other browsers would be helpful (if you have any Firefox extensions installed, try disabling those as well). Also, it'd be good to see how the statement is stored in the database.

```ruby
Blazer::Query.find(query_id).statement
```

**Comment by klarazetkin** [comment]
Thank you, will try a different browser and will try disabling Firefox extensions. 

> Also, it'd be good to see how the statement is stored in the database.

This query:

![image](https://user-images.githubusercontent.com/38485331/170020981-433d7236-fc2c-4926-9876-5186ccf0e581.png)

Looks this way in the database:

```
irb(main):019:0> Blazer::Query.find(query_id).statement
=> "SELECT AVG(avg_income) AS avg_income\r\nFROM (\r\n    SELECT SUM(avg_income) AS avg_income\r\n    FROM ad_units\r\n    WHERE deleted_at IS NULL\r\n    AND avg_income > 0\r\n    GROUP BY publisher_id\r\n) AS earning_publishers_income"
```

**Comment by ankane** [comment]
The database value looks good, so seems like something else is causing it.

**Comment by ankane** [comment]
Cleaning up issues. Seems like it may be specific to your installation, but will be on the lookout for similar reports.

**Comment by klarazetkin** [comment]
Hey-hey, sad to say, the issue remains. It's persistent with both Firefox and Chrome with all extensions disabled. Might it be connected to the way blazer is integrated into our application? Is there anything we can check on our side?
