### ISSUE TITLE
[Idea] Allow user to choose graph or table to be displayed on a dashboard

### ISSUE THREAD

**Issue by klarazetkin** [ankane/blazer#400]
A user should be able to choose whether to display a graph or a table for a certain query. Sometimes user might want to display only tables, e.g. if graphs are not informative. 

![image](https://user-images.githubusercontent.com/38485331/169809774-dfce9f71-a315-48bf-bcec-b70cceb3c45d.png)

**Comment by ankane** [comment]
Hey @klarazetkin, thanks for the suggestion. You can cast one of the columns so it no longer matches the chart format.

**Comment by klarazetkin** [comment]
Thank you for idea! I'm successfully working it around. :)
