### ISSUE TITLE
ActionView::Template::Error (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by Emerson89** [ankane/blazer#405]
I have this error at the time of trying to run a "new query"

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    19:             <a :href="schemaPath" target="_blank" style="margin-left: 40px;">Schema</a>
    20:           </div>
    21:
    22:           <%= f.select :data_source, Blazer.data_sources.values.select { |ds| q = @query.dup; q.data_source = ds.id; q.editable?(blazer_user) }.map { |ds| [ds.name, ds.id] }, {}, class: ("hide" if Blazer.data_sources.size <= 1), style: "width: 140px;" %>
    23:           <div id="tables" style="display: inline-block; width: 250px; margin-right: 10px;">
    24:             <select id="table_names" style="width: 240px;" placeholder="Preview table"></select>
    25:           </div>

**Comment by ankane** [comment]
Hey @Emerson89, can you paste the full backtrace?

**Comment by Emerson89** [comment]
Resolved
