### ISSUE TITLE
[Idea] Live queries or refresh frequency

### ISSUE THREAD

**Issue by juanmanuelramallo** [ankane/blazer#408]
## Why
Because when building monitoring dashboards it makes sense to have the data be refreshed automatically after some period of time.

## What
Allow dashboards/queries to be configured with a "Refresh data frequency" attribute that makes the query/dashboard be rerun at the time frequency specified, i.e. 30s, 1m, 5m, 10m, etc

## What do you think?
Is this a feature that would make Blazer a more compelling tool for your needs? 

I'd be more than happy to take a stab at the implementation but I'd love to get some feedback first.

**Comment by ankane** [comment]
Hey @juanmanuelramallo, thanks for the suggestion, and sorry for the delay. I've explored this in the past, but think there are better tools for live dashboards like [Smashing](https://github.com/Smashing/smashing) (so don't really want to include it right now).

**Comment by juanmanuelramallo** [comment]
TIL about Smashing, will try it out. 

Thanks for Blazer.
