### ISSUE TITLE
Cyrillic causes an error

### ISSUE THREAD

**Issue by klarazetkin** [ankane/blazer#409]
Blazer queries cannot handle cyrillic strings in clauses. 

Steps to reproduce: try to select anything from any table `WHERE text_field LIKE "%любойтекст%"` or `WHERE text_field = 'текст'` and the error will appear.

![image](https://user-images.githubusercontent.com/38485331/183151507-ae845ca1-1a22-49aa-bc52-64ef52d570ab.png)
![image](https://user-images.githubusercontent.com/38485331/183151612-d56ccde8-a43b-4f01-9560-97668acec0f2.png)

**Comment by ankane** [comment]
Hey @klarazetkin, I'm not able to reproduce. Can you paste the stack trace?

**Comment by klarazetkin** [comment]
Unfortunately, I'm not sure how to get the stack trace. If no tips, I'll ask our devs in the morning. :)

**Comment by ankane** [comment]
It should be in the application logs (you'll probably need a dev to access it).

**Comment by klarazetkin** [comment]
Hey, please, don't close the issue. We're doing hard to check it, lol.

**Comment by ankane** [comment]
Cleaning up stale issues - can reopen if there's more info to reproduce
