### ISSUE TITLE
Pagination does not currently work

### ISSUE THREAD

**Issue by gotoAndBliss** [ankane/blazer#420]
I believe this is easily remedied.

We have a limit set at (1000)

```
module Blazer
  class QueriesController < BaseController
   ...
    def home
      set_queries(1000)
```

But in `home.html.erb`, we only only show `200`

```
    computed: {
      visibleItems: function () {
        // hack to get to update
        this.updateCounter

        var pageSize = 200
```

Which means if you have more than 200 queries, this line :

```
307: @more = limit && @queries.size >= limit
```

Will return `false` effectively turning off pagination. So the only way to make pagination work after you make more than 200 queries, is to make 1000 queries.

Or we make the Rails SetLimit(n) == the Pagination limit in the JS

**Comment by gotoAndBliss** [comment]
Setting the pageSize to 1000 to equal the `set_queries` does the trick for me.

**Comment by ankane** [comment]
Hey @gotoAndBliss, I'm not sure I follow. There's no pagination (just a limit of 200 in JavaScript).
