### ISSUE TITLE
[Idea] Add string column for message to checks

### ISSUE THREAD

**Issue by gabrieltaylor** [ankane/blazer#429]
Hi, Blazer Team!

We use Blazer checks a lot and would like to be able to link to a run book in a failing check Slack message or email. This could make the failing check more easily actionable. I think a 255-character string field would be sufficient and provide users the flexibility to add a description, a link to a run-book, emojis, etc., to the slack or email message.

If you are open to incorporating this feature, I'd like to volunteer to create the PR.

**Comment by cianmce** [comment]
It's not the perfect solution, but for us we use "bad data" checks and have the start of the query like
```sql
SELECT  "https://example.com/page?runbook" AS runbook_url, id, ...
```

**Comment by gabrieltaylor** [comment]
I didn't even consider that @cianmce. Nice tip.

**Comment by ankane** [comment]
Hey @gabrieltaylor, thanks for the suggestion. You can also use the query description field to add instructions, so don't think an additional field is needed.

**Comment by gabrieltaylor** [comment]
@ankane what are your thoughts on adding the query description to the slack message or email? Are you be interested in incorporating that feature?

**Comment by ankane** [comment]
I don't think it's really needed, since you'll typically want to open the check page (to re-run it) to get the current state of things (and it'll be there), but you can always fork and add it for your application.
