### ISSUE TITLE
[Idea] Support for Redis as a data source?

### ISSUE THREAD

**Issue by gsdean** [ankane/blazer#432]
Not sure how/if this would work based on the existing data source design. It does feel like hole in the capabilities that would be great to fill. 

Has there been any attempt? 
Are there known issues/gotchas? 
Is there an appetite in a PR?

**Comment by ankane** [comment]
Hi @gsdean, thanks for the suggestion, and sorry for the delay. It's not something I'd like to include in Blazer right now, but you could create a [custom adapter](https://github.com/ankane/blazer#creating-an-adapter) for it.
