### ISSUE TITLE
Ambiguous BaseController

### ISSUE THREAD

**Issue by atagunay** [ankane/blazer#433]
Hello there, 

First of all, Thanks for the amazing gem.

If your project has a class called BaseController, which I also have, the interpreter is confused.

<hr>

**For example:**

1. This is my base controller

```ruby
class Admin::BaseController < BaseController
```

2. And this is gem's base controller

```ruby
BaseController < ApplicationController
```

3. This is the error
<img width="871" alt="image" src="https://user-images.githubusercontent.com/69992550/229182952-79964a67-931c-438a-8e97-4194e8e236ae.png">

**Comment by ankane** [comment]
Hi @atagunay, I'm not sure how to reproduce, but think it's something specific to your application. `BaseController` refers to `Blazer::BaseController` when nested in the `Blazer` module, so it's not ambiguous.
