### ISSUE TITLE
[idea] Implement autosave to local storage for queries

### ISSUE THREAD

**Issue by acuppy** [ankane/blazer#436]
I recently lost a query I was putting together when I stopped the server before I hit save. I don't think it is a bug of any kind, but I realized there might be value for local storage of the `query_statement` text area. Won't be fool proof, but it might prevent some heartache for a few.

**Comment by ankane** [comment]
Hi @acuppy, thanks for the suggestion. This was considered in the past, but was never released due to https://github.com/ankane/blazer/pull/182#issuecomment-403667754.
