### ISSUE TITLE
[idea] specify url options when crafting a url for slack notification

### ISSUE THREAD

**Issue by adamzapasnik** [ankane/blazer#442]
Hi,

https://github.com/ankane/blazer/blob/master/lib/blazer/slack_notifier.rb#L66-L68

Correct me if I'm wrong, but there is no way of configuring this atm, right? If so, would you be okay with reviewing a PR for this?

**Comment by ankane** [comment]
Hi @adamzapasnik, it'll use the same options as your mailers. I don't think it's common enough to have a separate option, but you can always fork for your application.
