### ISSUE TITLE
[3.0.0] Blank page on new query

### ISSUE THREAD

**Issue by CROUZET** [ankane/blazer#446]
Hello,

bumping Blazer from 2.6.5 to 3.0.0.

Blank page and error triggered in the console when accessing url: <local_env>/blazer/queries/new
```
new:72 Uncaught TypeError: Vue.createApp is not a function
    at new:72:17
```

Same error using Firefox, chrome or Vivaldi

same error with blazer's 'master' branch.

Back to normal when downgrading to 2.6.5

Thanks!

**Comment by ankane** [comment]
Hi @CROUZET, I'm sure how to reproduce, but it sounds like the assets may be outdated. Try clearing them with `rails assets:clobber`.

**Comment by CROUZET** [comment]
Thx a lot Ankane, it worked :)
