### ISSUE TITLE
suser specific db access

### ISSUE THREAD

**Issue by sopnaarth** [ankane/blazer#450]
Hi,

without blazer/docker if im taking this repo source code and deploying it ,can i able to do multiple authentication also is it possible to restrict specific database for users? example user 1 can access 3 out of 5 database. if so please guide where can i change the code .

**Comment by ankane** [comment]
Hi @sopnaarth, check out [this section](https://github.com/ankane/blazer#authentication) for authentication. There's not a way to restrict databases for users.
