### ISSUE TITLE
[Questions] Version control queries + Slack notification setup

### ISSUE THREAD

**Issue by pil0u** [ankane/blazer#456]
Hi @ankane,

Thanks a lot for your projects and making them open source. I am using strong_migrations and blazer in an open source Rails project, it's a blast 🙌 

I have two (unrelated to each other) questions:

1. ~~Is there a typical process to version control queries, where I could write/design an SQL query in dev, commit it to the repo, and make it accessible in Blazer in prod seamlessly?~~
**Edit: Eventually, it does not really make sense**

2. I have tried to setup Slack notifications with an incoming webhook for checks, but I might be missing a piece of the puzzle. Here are the steps I followed:

    1. In `blazer.yml`, I uncommented slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>
    2. I added my webhook in my `.env` file locally `BLAZER_SLACK_WEBHOOK_URL=https://hooks.slack.com/services...`
    4. I created a (failing) check and configured it like this: <img width="456" alt="Screenshot 2023-11-16 at 16 05 47" src="https://github.com/ankane/blazer/assets/8350914/20eff996-18a8-478d-bdbf-fbf5e454e956">

As you can see, I tried multiple identifiers for the Slack channel, but nothing pops in. The webhook is tied to this channel and it works, I tried with a basic `curl` command. But not through Blazer. What am I missing?

`blazer (3.0.1)`

Thank you!

**Comment by ankane** [comment]
Hi @pil0u, I'm not sure why it wouldn't be working for your application, but you could try using the OAuth approach: https://github.com/ankane/blazer/pull/368#issuecomment-990559373

**Comment by pil0u** [comment]
Hey man, I managed to make it work somehow (3.0.4). Using the correct channel names helped.

Also, I had to set
```ruby
config.action_mailer.default_url_options = { host: "dummy_host" }
```
to make it work as well. I am not using ActionMailer in my app, but [this bit](https://github.com/ankane/blazer/blob/v3.0.4/lib/blazer/slack_notifier.rb#L66-L68) requires it for Slack alerts, unsure if this is a bug or a feature.
