### ISSUE TITLE
[Idea] Using blazer with a DuckDB adapter

### ISSUE THREAD

**Issue by reel** [ankane/blazer#458]
Hi! 

DuckDB is a really fast way to query data (CSV, JSON, Parquet) locally and remotely. A DuckDB connector would be an awesome addition to this great gem.

**Comment by ankane** [comment]
Hi @reel, thanks for the suggestion, and sorry for the delay. It's not something I'd like to include right now, but someone could create a [custom adapter](https://github.com/ankane/blazer?tab=readme-ov-file#creating-an-adapter) for it.
