### ISSUE TITLE
Best practices in production

### ISSUE THREAD

**Issue by jimleroyer** [ankane/blazer#463]
Hi!

Thank you for your project, we very much like it in our organization for its ability to build and share queries among developers.

I have questions around best practices in production and it's not related to a bug or requested feature. Please redirect me if this is the wrong place to ask or if it has been answered. I could help contributing to a wiki with answers provided if deemed useful and desired.

My questions would be around the usage of Blazer in production. I want to know how users of Blazer uses it to isolate or mitigate production issues that could be be caused by non-optimized and long running queries.

* Does people install Blazer in a production environment to begin with?
* If yes, to whom would you provide access? do you tightly control this to a DB admin only who knows the ins and outs of the database schema? or more loose to developers who might know a bit more but are no DB experts? I wonder what are the best practices of the Blazer community, for which use cases do they have Blazer for?
* Do you isolate Blazer access to a database read instance to mitigate production impact?
* Do you isolate Blazer access to a different cluster to which data is being replicated to, to minimize further a potential impact by Blazer?
* Do users have a review process for the written queries and potential impact on the database performance?

I think answers to these might vary depending on the nature of the database and its business risk. But I wonder, when there are is risk of a production impact with Blazer, what are the best practices involved to mitigate that risk across the database that the Blazer community might promote?

Sorry if that's the wrong place, and it's sort of open ended with how one might feel comfortable with their production environment and team. 

Regards

**Comment by blairanderson** [comment]
Hi @jimleroyer i'll add some answers here. 

1. Yes people use this in production. Entirely depends on your company. Use encryption if you have sensitive data and it won't be an issue who has access. 
2. Anyone you want. Most data analysts have access to database. 
3. depends on your workload. Tiny companies don't need to separate it. bigger teams or slower queries will need isolation. 
4. there is no review process. Sidebar shows who created the query but nothing bigger

**Comment by ankane** [comment]
Thanks @blairanderson!
