### ISSUE TITLE
TypeError: Vue is not a constructor

### ISSUE THREAD

**Issue by sedubois** [ankane/blazer#465]
The Blazer dashboard stays stuck on "Loading..." and the JS console shows `Uncaught TypeError: Vue is not a constructor`. The stack trace points to HTML line 87:

```
  var app = new Vue({
    el: "#queries",
    data: {
      searchTerm: "",
      more: more,
      updateCounter: 0
    },
  ...
```

The same error shows up when I click New Query.

I did not find particular installation or migration instructions related to Vue.js in the README, would you have any hints?

Using Blazer 3.0.3.

**Comment by sedubois** [comment]
As a workaround, the issue is "fixed" when downgrading from Blazer 3.0.3 to 2.6.5. Then the Blazer queries show up and new queries can be created.

**Comment by ankane** [comment]
Hi @sedubois, `new Vue(...)` isn't present in 3.0.3, so think it's something specific to your application.

**Comment by sedubois** [comment]
I see the code changed in v3:

https://github.com/ankane/blazer/commit/693d31d711129264df1292c466a55ac53383bda6#diff-10b88f6cb284838662e169dc198eb0232bcf568ef19ba6afc268f92e2417567aL37

![Screenshot 2024-01-22 at 10 09 13](https://github.com/ankane/blazer/assets/4217871/d0cb4409-eba2-4860-a13c-c9436a0e6664)

For some reason the view from version 2.6.5 keeps being rendered even when using gem version 3.0.3. Error happens in prod and dev. I tried:
- clearing the repo's `tmp` folder
- using a private browsing session with all browser cache disabled
- using different browser

**Comment by sedubois** [comment]
Found it: that specific view (`app/view/blazer/queries/home.html.erb`) was overridden by our application. Sorry for the noise!
