### ISSUE TITLE
[Idea] New / Edit state stored in localstorage

### ISSUE THREAD

**Issue by RStankov** [ankane/blazer#472]
Hi,

Thanks for your work. Blazer is one of the first gems I add to any new project 🙌

**Problem**

When working on complex queries, I spend 10-20 minutes in a new/edit form. Then, for some reason, I click back or close the tab and lose the query.  🫣

**Solution**

The form's contents can be stored in localStorage or sessionStorage, so it will remain there when we re-open the form.

If you find this useful, I can open PR for it.

**Comment by ankane** [comment]
Hi @RStankov, check out #436.

**Comment by RStankov** [comment]
I see. Thanks for explaining.
