### ISSUE TITLE
Back Button is not rendering UI when validations failed while creating/updating Query/Dashboard

### ISSUE THREAD

**Issue by pandu-49** [ankane/blazer#476]
Back link/button provided while creating or updating a query/dashboard is not rendering UI when below scenario is executed.

Steps to Reproduce:
- Click on New Query
- Submit the form without providing proper values. Ex: Blank Name
- Click on Back link/button (This navigates to new query page)
- Click on Back link/button after redirection is completed. 
- Above click should have redirected to Home page but it rendering a json data.

Thanks!

**Comment by ankane** [comment]
Hi @pandu-49, thanks for reporting. Fixed in the commit above.
