### ISSUE TITLE
How do I create a dashboard

### ISSUE THREAD

**Issue by onlyyouandty** [ankane/blazer#48]
I have seen an example of queries in a dashboard here: https://blazerme.herokuapp.com/dashboards/1-movielens.

But I don't know how to go about this. 

Btw: this is a very useful reporting tool.

**Comment by jonahgeorge** [comment]
Within the main dropdown menu, select the "New Dashboard" item. From there, just select the charts that you want displayed on the dashboard.

<img width="596" alt="screen shot 2016-02-28 at 9 31 52 am" src="https://cloud.githubusercontent.com/assets/2058205/13380718/3a266ec2-ddfe-11e5-9a91-da8cd0799e91.png">

**Comment by onlyyouandty** [comment]
I can't seem to find a dropdown on the blazer configured to my application. How come?

![screenshot from 2016-02-29 14 37 59](https://cloud.githubusercontent.com/assets/7871367/13395955/2fcedbb8-def2-11e5-9394-5a6eff8f2f25.png)

**Comment by jonahgeorge** [comment]
Which version are you currently running?

**Comment by onlyyouandty** [comment]
I see. Seems like "blazer (0.0.5)"
