### ISSUE TITLE
[Idea] Multi line charts support with multiple quries

### ISSUE THREAD

**Issue by eslamodeh** [ankane/blazer#480]
Hello,

Is it possible to merge multiple line charts to one chart? Or for example, have two select query that would show two line charts?

**Comment by ankane** [comment]
Hi @eslamodeh, you'd need to write it as a single query. For Postgres, you can use `UNION ALL` to combine two `SELECT` queries.

```sql
SELECT time_column_a AS time, 'Series A' AS series, numeric_column_a AS value FROM ...
UNION ALL
SELECT time_column_b AS time, 'Series B' AS series, numeric_column_b AS value FROM ...
```
