### ISSUE TITLE
Check not triggered until I went for it

### ISSUE THREAD

**Issue by pil0u** [ankane/blazer#484]
Hello,

A couple of weeks back, I set up 6 checks on my app that would send me a Slack notification when failing. When I set them up, I carefully made sure that the system worked, and it worked.

All checks are set to refresh every 5 minutes.

I have a check that is supposed to fail when I reach 300 users. My app showed that there were 330+ for hours, but the check did not trigger. So I went to Blazer, and the moment I visited the Checks page, that particular check failed and the notification was triggered immediately.

Would you have an idea why would that happen? My suspicion is that the `state` of a check might reset somehow, maybe upon redeploy, and you have to manually trigger them once again to "reactivate" them.

I suppose it's hard to reproduce, but I thought I'd still mention that as an issue, as the feature does not really work as expected. Upon my future release, I will carefully look at the states of the checks in the database and report back if I see something unusual.

**Comment by cianmcelhinney** [comment]
> Hello,
> 
> A couple of weeks back, I set up 6 checks on my app that would send me a Slack notification when failing. When I set them up, I carefully made sure that the system worked, and it worked.
> 
> All checks are set to refresh every 5 minutes.
> 
> I have a check that is supposed to fail when I reach 300 users. My app showed that there were 330+ for hours, but the check did not trigger. So I went to Blazer, and the moment I visited the Checks page, that particular check failed and the notification was triggered immediately.
> 
> Would you have an idea why would that happen? My suspicion is that the `state` of a check might reset somehow, maybe upon redeploy, and you have to manually trigger them once again to "reactivate" them.
> 
> I suppose it's hard to reproduce, but I thought I'd still mention that as an issue, as the feature does not really work as expected. Upon my future release, I will carefully look at the states of the checks in the database and report back if I see something unusual.

How are you running the checks? Eg are you using the Sidekiq or Heroku or something to run on a schedule to execute the checks?
> https://github.com/ankane/blazer/tree/9c1c5a6639dcfe40d5d4c273f26142418c4f8248?tab=readme-ov-file#checks-optional

**Comment by cianmce** [comment]
> Hello,
> 
> A couple of weeks back, I set up 6 checks on my app that would send me a Slack notification when failing. When I set them up, I carefully made sure that the system worked, and it worked.
> 
> All checks are set to refresh every 5 minutes.
> 
> I have a check that is supposed to fail when I reach 300 users. My app showed that there were 330+ for hours, but the check did not trigger. So I went to Blazer, and the moment I visited the Checks page, that particular check failed and the notification was triggered immediately.
> 
> Would you have an idea why would that happen? My suspicion is that the `state` of a check might reset somehow, maybe upon redeploy, and you have to manually trigger them once again to "reactivate" them.
> 
> I suppose it's hard to reproduce, but I thought I'd still mention that as an issue, as the feature does not really work as expected. Upon my future release, I will carefully look at the states of the checks in the database and report back if I see something unusual.

How are you running the checks? Eg are you using the Sidekiq or Heroku or something to run on a schedule to execute the checks?
 - https://github.com/ankane/blazer/tree/9c1c5a6639dcfe40d5d4c273f26142418c4f8248?tab=readme-ov-file#checks-optional

**Comment by ankane** [comment]
Hi @pil0u, it's likely what @cianmce mentioned. Checks will also run manually when the query is run, which can trigger notifications.

**Comment by pil0u** [comment]
Hey @cianmce & @ankane, thank you for the suggestion, that was it.

I somehow assumed the scheduling was managed by Blazer 🫣 

Essentially I built a Job and used my ActiveJob backend ([GoodJob](https://github.com/bensheldon/good_job#goodjob)) to trigger it on a regular schedule:

```ruby
# app/jobs/blazer/run_all_checks_job.rb

module Blazer
  class RunAllChecksJob < ApplicationJob
    def perform
      Blazer.run_checks
    end
  end
end

# config/initializers/good_job.rb

Rails.application.configure do
  config.good_job = {
    execution_mode: :external,
    max_threads: 5,
    shutdown_timeout: 30,
    enable_cron: true,
    cron: {
      blazer_run_all_checks: {
        cron: "*/5 * * * *",
        class: "Blazer::RunAllChecksJob"
      }
    }
  }
end
```

Obviously you'd need a fancier way to handle a `SCHEDULE` parameter, but running all my checks every 5 minutes works out for me 👍 (and removed all other options in the YML config).
