### ISSUE TITLE
Blazer unexpectedly hijacks popular keyboard shortcut Cmd+L

### ISSUE THREAD

**Issue by meetrajesh** [ankane/blazer#53]
Cmd+L is a popular browser keyboard shortcut to move focus to the URL bar. Currently blazer hijacks this to help you navigate to a specific line. Perhaps we could use an alternate keyboard shortcut like Ctrl+g (like Sublime) for this?

**Comment by ankane** [comment]
Should no longer hijack - cc @sferik

**Comment by meetrajesh** [comment]
Thank you, sir!
