### ISSUE TITLE
Error with smart variables and regular expressions

### ISSUE THREAD

**Issue by strivedi183** [ankane/blazer#54]
First off, awesome project, thanks!

Using the blazer example app on heroku - https://blazerme.herokuapp.com/queries/new

If we wanted to find a movie with the word 'yao' in the title, we can do

```sql
SELECT * FROM movies
WHERE title ~ 'yao';
```

Works and returns the movie with the title "Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)"

But if we use a regex to find 'yao yao ' in the title using a bound (http://www.postgresql.org/docs/current/static/functions-matching.html)

```sql
SELECT * FROM movies
WHERE title ~ '(yao ){2}';
```

We should get the same result as above but instead we get "Can’t preview queries with variables...yet!" message

I think that the `extract_vars` method in the base_controller is looking for any left curly brace (https://github.com/ankane/blazer/blob/master/app/controllers/blazer/base_controller.rb#L46)

Not really sure the best way to deal with that. Our hack was just add some code that ignores smart variables in a line if they come after a the tilde but we'd like to be able to use smart variables everywhere. What about maybe using double instead of single curly braces so `extract_vars` method can know it's supposed to be a smart variable? Or whatever other suggestions you all might have

Thanks again!

**Comment by ankane** [comment]
Thanks for the detailed report Sandip.  I think the best approach is to skip variables that match patterns like `{1}` and `{1,2}`.  It's not 100% backwards compatible, but I think it should be safe in most cases.
