### ISSUE TITLE
Creating Public / Sharable Pages

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#56]
This one comes from Heroku's "Dataclips" feature. 

I'd like to _optionally_ be able to designate a dashboard / query as 'public' which would allow the page to be visited even if there's a `before_filter` active. This would make sharing some analysis easy, without needing to give users full admin access.

Bonus points that'd be cool:
- The CSV export URL could be public. (This would allow embedding CSV data in a Google Sheet, which is also a neat little trick. Heroku Dataclips does this.)
- Make the public pages read only if not logged in.
- Make the public pages not indexable by google

**Comment by blairanderson** [comment]
design:
- `allow_public` config, default to false
- add column `public` boolean to queries, default to false
- add column `obscure_id` to queries, on create with SecureRandom
- add route to `ExportsController` if allow_public config is true
- respond to formats CSV/JSON

**Comment by FanaHOVA** [comment]
@cycomachead @blairanderson not sure if you guys are still interested in this, giving it a shot in this PR, hoping to have it done by the end of the week! https://github.com/ankane/blazer/pull/153

**Comment by ankane** [comment]
Cleaning up issues. For future readers, see https://github.com/ankane/blazer/pull/153#issuecomment-451785361.
