### ISSUE TITLE
Creating Charts with Non-String X-Axis

### ISSUE THREAD

**Issue by cycomachead** [ankane/blazer#57]
From my understanding of the current views, it seems like I can only create bar charts if the type for the column is a string? Is there a reason this couldn't work for integers or other numbers?

I'm currently using Postgres' `to_char()` functions, which seem to work OK. Was this the intention?
If not, I could look into making a PR. Otherwise, I think a bit of documentation in the README would be good. I'd really appreciate a table of Column Types vs Graph Types. 

Thanks for the awesome work though! 👍

**Comment by ankane** [comment]
@cycomachead I typically cast to a string with `some_number::text`. Two number columns should probably produce a scatter plot.

**Comment by cycomachead** [comment]
That would be helpful too, though in my case I think a bar chart is still preferred, but I definitely would see the use for scatter plots.

Would you accept a PR for a scatter plot?

Also, thanks for the `::text` tip. I also forget those conversions exist.

**Comment by ankane** [comment]
Thanks for offering 👍 

I'm planning to move Blazer to Chart.js (through Chartkick), which doesn't support scatter plots yet, so it'd probably be best to wait on this.

**Comment by ankane** [comment]
Also, if others have an opinion on scatter vs bar, please add your thoughts.
