### ISSUE TITLE
Index page not showing all queries

### ISSUE THREAD

**Issue by dgobaud** [ankane/blazer#61]
Just upgraded to Blazer 1.3.3 from 1.1. Some queries are no longer showing on the main page even though they exist. Also just made a new query it doesn't show up either. Everything shows up in the /queries json though.

**Comment by ankane** [comment]
Hey David, Blazer now just shows 200 at any given time (for browser performance).  You can use the search to narrow down queries.

**Comment by dgobaud** [comment]
I think something else is wrong. Search is actually limited too - queries that don't show in the list won't show up in search. We also only have 64 queries.

An option to show more (all) than 200 would also be great.

**Comment by ankane** [comment]
I'm not able to reproduce locally, but would be great if you could dig in more to see what's going on.

**Comment by dgobaud** [comment]
on the page queryValues only has 40 items even though I have 63 queries. Problem must be in set_queries here https://github.com/ankane/blazer/blob/master/app/controllers/blazer/queries_controller.rb

I can't tell exactly what it is doing - what does it try to exclude?

**Comment by dgobaud** [comment]
it seems like you're trying to exclude favorite ones? but why/where are they?

**Comment by ankane** [comment]
Ah, I see the issue. Will push a fix in a sec.

**Comment by ankane** [comment]
Excluding favorites was just a mistake. Will push a new release as well.  Thanks for all the help. 💯
