### ISSUE TITLE
deploying blazer into production

### ISSUE THREAD

**Issue by wolfieorama** [ankane/blazer#62]
Hi I have blazer running locally, but in production despite adding blazer.yml into my Capistrano linked files folder is still `BLAZER_DATABASE_URL required`

i already have this in my yml file 

`ENV["BLAZER_DATABASE_URL"] = "postgres://att_tra: att_tra@localhost/att_tra_production"` 

whats missing

**Comment by ankane** [comment]
Hi John, looks like that message was no longer needed. Should be removed on master. Thanks for reporting.
