### ISSUE TITLE
Queries with functions or conditions render as float number

### ISSUE THREAD

**Issue by bernardolm** [ankane/blazer#65]
Why queries with functions or conditions like that:

```
SELECT 
    CASE WHEN 1 > 2 THEN 'a1' ELSE 'a2' END AS a,
    CONCAT('a', 3) AS b
FROM dual
```

render like that:

```
a   b
-------
0.0 0.0
```

?

**Comment by ankane** [comment]
Hi @bernardolm, I'm unable to reproduce.  Can you provide more info?

**Comment by bernardolm** [comment]
Hi, @ankane. I simply created a query with this command that produce this result.

![view](https://cloud.githubusercontent.com/assets/305923/16463110/b29a1554-3e0a-11e6-9f42-cae7f3729d54.png)

There are two columns as char type and output like a float number in HTML view. Why?

**Comment by bernardolm** [comment]
Hi, @ankane. I simply created a query with this command that produce this result.

![captura de tela de 2016-06-29 15-02-55](https://cloud.githubusercontent.com/assets/305923/16464033/c55ad7e2-3e0e-11e6-8b09-ab81680d0ba9.png)

There are two columns as char type and output like a float number in HTML view. Why?

**Comment by ankane** [comment]
Very odd. What version of `rails` and either `mysql2` or `pg` are you using?

**Comment by bernardolm** [comment]
Ruby version 2.2.2
Rails version 4.2.5
And I use mysql2

Some concats (string and int) results a correct output but the same concat in other query, results in float output.

**Comment by ankane** [comment]
Hey @bernardolm, not sure I'll be able to debug this from afar very easily. I think you'll need to dig into the source to debug what's going on.

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by bernardolm** [comment]
@ankane I'll check this bug in new versions and back with feedback :+1:

**Comment by trevororeilly** [comment]
One thing to check out is the return type of the function you're calling. An example for PostgreSQL is that `sum` can return a different type than the underlying data:

https://www.postgresql.org/docs/11/functions-aggregate.html

> bigint for smallint or int arguments, numeric for bigint arguments, otherwise the same as the argument data type

So the sum of a `bigint` column would be returned as `numeric`, which would then be mapped to `BigDecimal` by ActiveRecord and displayed with a decimal by Blazer. 

A couple of options for tweaking display output are wrapping the function in `to_char` or casting the return value to `text`.

Hope that helps!
