### ISSUE TITLE
Dropdown in 'edit query' view is never populated

### ISSUE THREAD

**Issue by webdevotion** [ankane/blazer#68]
I would like to get some advice to fix my problem.

The dropdown under the query textarea on the `edit query` view is never populated, nor can I execute any queries.  Every query results in:

```sql
relation "table_name" does not exist LINE 1: select * from table_name; /*blazer*/ ^ :
select * from table_name; /*blazer*/
```

Example query which fails using Blazer, but works when executed in psql:

`select * from products;`

`select * from "public"."products";`

I created a `blazer` role, tried with the admin user, ... and am basically out of options.

Thank you.

**Comment by ankane** [comment]
It sounds like your Blazer credentials aren't matching your psql credentials.  Unfortunately, I don't have much time to help debug, but maybe someone else can jump in.

**Comment by webdevotion** [comment]
No problem.  I finally managed to get Blazer up and running.
