### ISSUE TITLE
Blazer is overriding Devise path

### ISSUE THREAD

**Issue by onlyyouandty** [ankane/blazer#73]
Hi, I just figured that blazer is overriding devise gem in my app. Everything works fine in development but in production here is the error when I clicked on the login button `undefined method 'session_path'` and when I click on the signup button, I get `undefined method 'registration_path' error`. 

After installing and uninstalling blazer gem, I figured out that was the reason. How do I solve this.

**Comment by cycomachead** [comment]
Were you overriding the layout file? To load blazer into your existing layout?

**Comment by cycomachead** [comment]
See this for my work around:
https://github.com/cycomachead/lambda/commit/34f2142ec21b37c7ba48909c3a1be5bf93d09d31#diff-84a1dcbd329840437c75e449802b9361R15

Though, it's not idea for a large app. :\

**Comment by onlyyouandty** [comment]
Hey @cycomachead. I'm not using the gem in the layout file or in the views of my application. I only have the gem in my `Gemfile` and `config/routes.rb`, so to my to my understanding, I am not overriding the layout file. Here was an issue on devise gem channel that gave me an idea that I might have  a mounted engine which was causing the error: https://github.com/plataformatec/devise/issues/1984.

**Comment by ankane** [comment]
Cleaning up stale issues
