### ISSUE TITLE
Charts not loading

### ISSUE THREAD

**Issue by coreymartella** [ankane/blazer#76]
Have a simple 2 column date+numeric query and the chart div just stays "loading" but the table data looks fine.

![monosnap 2016-08-02 11-13-45](https://cloud.githubusercontent.com/assets/15925/17334049/cd9c3294-58a2-11e6-9925-3a63373452d2.png)

Some kind of config I'm missing for chartkick or Chart.js ? There are no errors in the Chrome Console or in the rails log file

Relevant files to my setup: https://gist.github.com/coreymartella/765736733fae949a42d3b02852ce4836 

Thanks!

**Comment by ankane** [comment]
That's odd, charts should just work. If there are no errors, it seems like the JavaScript for charts is not being executed. Do you have any Chrome extensions that could be interfering?

**Comment by coreymartella** [comment]
Tried incognito and Firefox and both still had the problem. I use chartkick and Chart.js in other projects without any issues, although I noticed blazer vendors chartkick and Chart.js rather than asset pipeline. The herokuapp demo works just fine so its definitely something about my setup :(

**Comment by coreymartella** [comment]
Ugh. so dumb, I use Chartkick in this project and had `Chartkick.options[:content_for]` set. Apologies.

**Comment by ankane** [comment]
Glad you figured it out (would not have guessed that was the problem).  Blazer shouldn't be affected by your app settings if possible.  I'm working on moving the UI to React to see how it feels, which would completely remove the `chartkick` gem dependency and only use the bundled js.

**Comment by seanfcarroll** [comment]
+1 for moving to React!
