### ISSUE TITLE
Blazer 2.0

### ISSUE THREAD

**Issue by ankane** [ankane/blazer#80]
For 2.0
- [x] raise error for unknown data sources
- [x] adapters out of beta
- [ ] migration to get everyone on same schema - check timeouts, etc
- [x] release `async: true` option - requires a centralized cache store, so shouldn't make default

Before 2.0
- [x] cancel all queries on page nav
- [x] show schema
- [x] cancelable queries

Possibly

- [ ] better organization (maybe tags)
- [ ] verified queries (on `verify_archive` branch)
- [ ] advanced permission model (locking queries, etc)
- [x] move to Vue

**Comment by davidguthu** [comment]
@ankane what do you need help on?

**Comment by ankane** [comment]
Hey @davidguthu, thanks for asking. I created some new issues and tagged them as [help wanted](https://github.com/ankane/blazer/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). Let me know if you have any questions or initial ideas.

**Comment by JayTeeSF** [comment]
First, let me say, this software is great. Thanks for sharing!

That said, the #1 feature I'd like is "tags" ...being able to organize our queries. And second to that is "cancelable queries"

Again, thanks for all your great work!

**Comment by ankane** [comment]
Released 🎉
