### ISSUE TITLE
Unable to sign-in after installing

### ISSUE THREAD

**Issue by onlyyouandty** [ankane/blazer#83]
I have been unable to sign up and login in my app's production after installing blazer gem.

Here was the process I followed to install blazer:
```
1. add gem 'blazer' to Gemfile
2. bundle installed
3. ran rails g blazer:install
4. rake db:migrate
5.heroku run rake db:migrate
6. add BLAZER_DATABASE_URL: "postgres://user:password@hostname:5432/database" in my application.yml file
7. add BLAZER_USERNAME: "andrew" and BLAZER_PASSWORD: = "secret" in my application.yml file
```
Here is the screenshot of the error log (basicaly, Device's `session_path` could not be found)
![image](https://cloud.githubusercontent.com/assets/7871367/17804111/0a597ef6-65f2-11e6-9f8b-d7726eacfbaa.png)

**Comment by ankane** [comment]
Hey @onlyyouandty, is this the same as #73?

**Comment by onlyyouandty** [comment]
Yes @ankane. You can close one or link both up please.
