### ISSUE TITLE
Blazer doesn't update data_source url

### ISSUE THREAD

**Issue by Dadits** [ankane/blazer#84]
On production, i updated data_source url in env variable but Blazer still uses old one, and redeploy does not help, checking this variable in rails console shown that the variable was updated in rails environment, more of that `Blazer.settings.dig('data_sources', 'main', 'url')` shows new url, but when i try to connect to db it still uses the old one

**Comment by ankane** [comment]
Hey @Dadits, this sounds like a problem with your setup rather than Blazer. I'd make sure the `ENV` variable is updated on the server, and Rails has properly restarted.
