### ISSUE TITLE
smart_column not working

### ISSUE THREAD

**Issue by dgobaud** [ankane/blazer#86]
I have a column gender with values (NULL, 1, 2) - 1 is Male, 2 is Female, and NULL is Unknown and I want the string versions outputted. In blazer.yml I've tried making many gender smart variables but they all just show blank, 1, or 2 - none will show the string. below are some examples - instead of IN (1) etc I tried = 1 nothing works.

gender: "SELECT gender, (CASE WHEN {value} IN (1) THEN 'Male'
                                           WHEN {value} IN (2) THEN 'Female'
                                           ELSE 'Unknown'
                                     END)"

gender_id: "SELECT (CASE WHEN {value} IN (1) THEN 'Male'
                                           WHEN {value} IN (2) THEN 'Female'
                                           ELSE 'Unknown'
                                     END)"

gender_id: "(CASE WHEN {value} IN (1) THEN 'Male'
                                           WHEN {value} IN (2) THEN 'Female'
                                           ELSE 'Unknown'
                                     END)"

**Comment by ankane** [comment]
Hey @dgobaud, I just pushed an update to make it significantly easier to do this:

```yml
smart_columns:
  gender: {1: "Male", 2: "Female", null: "Unknown"}
```

**Comment by dgobaud** [comment]
👍

**Comment by abrambailey** [comment]
Hey @ankane, where do you actually add this code?

**Comment by ankane** [comment]
`config/blazer.yml`

**Comment by abrambailey** [comment]
Might be nice to have a place to configure this without requiring a re-deploy. Thanks!!
