### ISSUE TITLE
ActiveJob

### ISSUE THREAD

**Issue by woodhull** [ankane/blazer#90]
I noticed that the async mode is bound to sucker_punch and not documented. 

Does it work? Any reason a PR refactoring to use active job instead of suckerpunch directly might not be a good idea? We use sidekiq in our environment and would like to avoid adding another library.

**Comment by woodhull** [comment]
I looked at the code more closely for the async support. I'm not sure the advantage it offers by delegating query execution to sucker punch. 

I had imagined that using async: true would cause blazer to poll for a successful query result or return the result via websocket but it looks like the controller just loops until the query is complete?

We're trying to work around the issue that our load balancer will timeout requests before many queries have a chance to return a result.

**Comment by woodhull** [comment]
Nevermind, I've tested this code and now see how it works.

**Comment by ankane** [comment]
We use the async option at Instacart, but it's not officially supported at the moment. It may become the default in future versions of Blazer. The reason we went with polling instead of websockets is to keep the setup complexity small for other devs.
