### ISSUE TITLE
Colour palette

### ISSUE THREAD

**Issue by jalberto** [ankane/blazer#91]
each one of my queries with grouping is showing a very flat colour palette, usually first 2 are blue, and the rest are grey shades.

![screenshot from 2016-10-20 22-44-02](https://cloud.githubusercontent.com/assets/99927/19579135/ee95b30a-9716-11e6-8e95-5607da8c4971.png)

Is this a bug or intentional?

Thanks!

**Comment by ankane** [comment]
That's odd. The colors should match those in the demo. Not sure what would be causing that.

**Comment by jalberto** [comment]
@ankane anything I can do to help?

I used somethign like this in previous project to get some "random" colours based on string (so same string must have same colour)

    Digest::MD5.hexdigest(string)[0..5]

This will generate a valid hex that can be used in CSS, is very simple, but it works :)

**Comment by ankane** [comment]
Can you paste the Chartkick JavaScript returned from the server? (it's returned in an AJAX call)
