### ISSUE TITLE
ActionView::Template::Error (undefined method `back_url'.....

### ISSUE THREAD

**Issue by gbrl** [ankane/blazer#93]
Anyone seen this before? I searched through all issues and couldn't find anything. 

`ActionView::Template::Error (undefined method `back_url' for #<Blazer::QueriesController:0x007fa96c1efd08>):`

Not sure what's causing it. I might just fork the gem and take that `<%= link_to "Back", :back %>` out.

**Comment by ankane** [comment]
I haven't. From the Rails docs:

> Using a :back Symbol instead of an options hash will generate a link to the referrer (a JavaScript back link will be used in place of a referrer if none exists)

**Comment by schesnowitz** [comment]
New in 5.1         format.html { redirect_back(fallback_location: root_path) }

**Comment by ankane** [comment]
Cleaning up stale issues
