### ISSUE TITLE
Update to 1.7.2 crashes the query overview and query editor

### ISSUE THREAD

**Issue by Brutus9** [ankane/blazer#94]
Our blazer updated automatically on heroku from 1.7.0 to 1.7.2 The result was all our blazer queries were in accessible, the dashboards were visible but the stats on the dashboards were all not found. And the query editor broke. The results were the following pictures: 

![blazer_bug2](https://cloud.githubusercontent.com/assets/6098618/19863379/56f19ab0-9f94-11e6-9591-bad96e7d98b2.JPG)

![blazer_bug1](https://cloud.githubusercontent.com/assets/6098618/19863368/49a2170e-9f94-11e6-8902-d33354690f91.JPG)

**Comment by ankane** [comment]
Hey @Brutus9, thanks for reporting. A few questions:

1. Do you see any errors in the JavaScript console?
2. What do you mean by "automatically updated"?

From first glance, looks like an issue with your assets not being updated.

**Comment by ankane** [comment]
Hey, I've been able to reproduce. Will try to get a fix out tomorrow.

**Comment by ankane** [comment]
Pushed out a new release. Thanks again for reporting 👍

**Comment by Brutus9** [comment]
Awesome, thanks!

Sorry for the slow reply. Thanks for your help again.
