### ISSUE TITLE
Better organization

### ISSUE THREAD

**Issue by ankane** [ankane/blazer#99]
Would love a better way to organize queries. Would be great to support personal queries as part of this as well. I'm planning to test the concept of folders, but would be great to see how others would design this.

**Comment by davidguthu** [comment]
You have any thoughts on this from a UI perspective? I agree folders would be a great addition.

**Comment by roybotnik** [comment]
I was thinking of submitting a PR to add tagging. It would be a little more flexible than folders while giving the same results (categorizing). What do you think?

**Comment by ankane** [comment]
Tags could work as well. I've done some prototyping on the `folders` branch ([here's the diff](https://github.com/ankane/blazer/compare/folders)) fwiw.

**Comment by pedrocarmona** [comment]
would be nice to have same UI features as https://github.com/airbnb/superset

**Comment by fatkodima** [comment]
@ankane Any updates on this? It would be really nice to have some sort of tagging feature.
BTW, thanks for awesome gem!

**Comment by ankane** [comment]
Moved ideas to #24.
